### ISSUE TITLE
Project admin should be able to add existing users to its project

### ISSUE THREAD

**Issue by flavens** [dasch-swiss/knora-app#100]
**Is your feature request related to a problem? Please describe.**
Only system admins can add users to any projects. But the project admin should be allowed to do the same for their projects.

**Describe the solution you'd like**
A project admin can add existing users in its projects. System admin can keep the privilege to create a new user.

**Describe alternatives you've considered**
N.A.

**Additional context**
Spotted during the drafting of the test protocol document.

**Comment by kilchenmann** [comment]
This is an issue in knora-api. Only system admin is able to get a list of all users of the system.

**Comment by subotic** [comment]
So, you need the whole list, so that the ProjectAdmin can pick a user and add him to the project? I could add this.

**Comment by kilchenmann** [comment]
@subotic That would be great. 
Yes, similar to github, where you can add any existing user to a repository or to a team just by typing username or name.

**Comment by subotic** [comment]
It‘s merged. ProjectAdmin should now be able to get all users.

**Comment by kilchenmann** [comment]
Thanks @subotic. We will implement it into to the app asap.

**Comment by kilchenmann** [comment]
@subotic the implementation works but I figured out, that a project admin can create new user, which is good, but he can also set the new user as system admin, which shouldn't be possible. In the app I will disable the corresponding form element and I'll write an issue in knora-api

**Comment by flavens** [comment]
@kilchenmann what is the status of this issue? Still in progress due to (dasch-swiss/knora-api#1552) ?

**Comment by kilchenmann** [comment]
I think we can close this issue. dasch-swiss/knora-api#1552 has another topic and is part of the api. I solved the mentioned issue already in the app by disable system-admin toggle in user form.
