### ISSUE TITLE
Knora-app should also provide search results in the form of a (sortable) table

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#111]
**Is your feature request related to a problem? Please describe.**
A common feedback we get from **Salsah 1.5** is that the search results are somewhat frustrating. Because even if they look like a table, which is great, you can't sort the results according to the properties you passed as parameters for the query.

![Capture d’écran 2019-10-15 à 15 50 36](https://user-images.githubusercontent.com/17294309/66838234-9fe71380-ef64-11e9-9678-d529c690ee38.png)

For now, the search results in **Knora-app** are not displayed in the form of a table.

**Describe the solution you'd like**
1. A table form would is in some cases the most efficient layout.
2. A sortable table would make the search results usable (ascending and descending order for each `TextValue`, `DateValue`, etc.).

**Describe alternatives you've considered**

**Additional context**
Here is an example for https://boccacciocommedia.unil.ch/varianti.php .

![Capture d’écran 2019-10-15 à 16 04 05](https://user-images.githubusercontent.com/17294309/66838702-71b60380-ef65-11e9-9379-0fc2ddc691dd.png)

**Comment by kilchenmann** [comment]
There are two problems at the moment:
- The Knora-api returns always the first 25 search results only. When you sort, it will take effect only on these 25 results.
- How to sort in case of different ressource-classes with different properties?

A table view will be integrated (similar to salsah's tableedit) and will be active, if filtered by one ressource-class. See [dasch-swiss/knora-ui#183](https://github.com/dasch-swiss/knora-ui/issues/183)

**Comment by mrivoal** [comment]
> - The Knora-api returns always the first 25 search results only. When you sort, it will take effect only on these 25 results.

But the `sort criterion` you implemented already works on the whole results given by knora-api. So I don't see why it wouldn't work (or would work in a different way) by clicking on the header of a column? 

> - How to sort in case of different ressource-classes with different properties?

I think it could start small and provide the table view only when a query is processed on one resource class. Only after could we try and figure out how to present search results under table form for cross resource queries. 

I see now that this is what dasch-swiss/knora-ui#183 is about. Great!

**Comment by kilchenmann** [comment]
> But the sort criterion you implemented already works on the whole results given by knora-api. 

Yes it's true, we can use it. But this will make new search requests (with gravsearch) on each click on sort button. But it will not work on fulltext-search results with various resource-classes because of the mixture of property-classes. But we will implement a faceted search, so you can filter and finally sort. This should be possible after implementing the knora-api-js-lib.

> I think it could start small and provide the table view only when a query is processed on one resource class.

Yes, this is exactly what I meant with "filtered by one ressource-class".

**Comment by mrivoal** [comment]
> -  But it will not work on fulltext-search results with various resource-classes because of the mixture of property-classes. 

I don't think the table view will be that useful for the full-text search. I think it will be useful mainly  for people who already know what they are looking, which means queries involving:
- one resource and selected properties on this resource 
- several resources involving various properties (but we have to figure out how to represent graph data on a tabular form)

But to refine the full-text search results, a faceted search will be great.

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-291](https://dasch.myjetbrains.com/youtrack/issue/DSP-291)
