### ISSUE TITLE
Add Bazel build tool support

### ISSUE THREAD

**Issue by subotic** [dasch-swiss/knora-app#116]
For Angular, adding Bazel should be fairly straightforward: https://angular.io/guide/bazel

**Comment by kilchenmann** [comment]
Adding bazel doesn't seem to be quite easy to implement. There are some issues with sass/scss especially with the material theming and with @angular/flex-layout.

I tried to fix it by following these issues:
- [@angular/flex-layout: Bazel install fails](https://github.com/angular/flex-layout/issues/1086)
- [bazelbuild/rules_sass: Add example of how to import from Angular Material's SASS stylesheets](https://github.com/bazelbuild/rules_sass/issues/98)
- [bazelbuild/rules_sass: Include_Import_issue](https://github.com/bazelbuild/rules_sass/issues/69)

But `ng s` or  `ng build --leaveBazelFilesOnDisk` still failing. I got the following errors:

```
ERROR: knora-app/src/BUILD.bazel:26:1: Compiling Sass failed (Exit 65)
Error: Can't find stylesheet to import.
  ╷
6 │ @import 'external/npm/node_modules/@angular/material/theming';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src/assets/style/_theme.scss 6:9             @import
  src/app/main/login/login.component.scss 1:9  root stylesheet

Error: Can't find stylesheet to import.
  ╷
1 │ @import 'external/npm/node_modules/@angular/material/theming';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src/app/project/ontology/ontology.component.scss 1:9  root stylesheet

[...]
```

I'm working on branch [wip/add-bazel](https://github.com/dasch-swiss/knora-app/tree/wip/add-bazel)

**Comment by subotic** [comment]
Great, thanks. I will take a look. At first glance, this looks like a dependency configuration issue. Bazel is building everything in a sandbox, and if the external dependencies are not configured correctly, then stuff is missing in the sandbox.

**Comment by kilchenmann** [comment]
All you have to know about bazel:
https://youtu.be/J1lnp-nU4wM
or in the summary:
https://youtu.be/wYUQ0RtN7oc

Btw I will try to implement again after adding knora-api-js-lib

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-283](https://dasch.myjetbrains.com/youtrack/issue/DSP-283)
