### ISSUE TITLE
Home button missing?

### ISSUE THREAD

**Issue by GabyKuster** [dasch-swiss/knora-app#128]
When I navigate in the knora-App, I would be able to move easily back to the initial page. Unfortunately I cannot find a button "Home"

**To Reproduce Steps to reproduce the behavior:**

**OPTIONAL: Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem (drag-and-drop the image directly here).

**Desktop (please complete the following information):**
* OS: Windows 10 Pro N, 1903 - 18362.418
* Browser Google Chrome, 78.0.3904.87

* Version Knora App, 1.6.2

**Additional context**
related to #211

**Comment by flavens** [comment]
this issue has been moved to YouTrack: https://dasch.myjetbrains.com/youtrack/issue/DSP-288
