### ISSUE TITLE
Homepage Knora-App

### ISSUE THREAD

**Issue by GabyKuster** [dasch-swiss/knora-app#130]
When checking the Knora-App Hopepage, I am not really sure, what the overall purpose of the page there is in my eyes a too large variety of information and services combined in one set:
- some aspects of the software (but I myself mitt the big picture of it)
- Quicksearch of "what data a user has" with links to NIE-INE and Fors (but nothing else)
- Projects in Knora
- Search in Projects

The general Layout design is quite nice, but the content should be more structured to clear information packages and easily navigatable positions . And I would really like less scrolling to find out what else is on the page.

**To Reproduce Steps to reproduce the behavior:**

**OPTIONAL: Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem (drag-and-drop the image directly here).

**Desktop (please complete the following information):**
* OS: Windows 10 Pro N, 1903 - 18362.418
* Browser Google Chrome, 78.0.3904.87

* Version Knora App, 1.6.2

**Additional context**

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-287](https://dasch.myjetbrains.com/youtrack/issue/DSP-287)
