### ISSUE TITLE
Typo: humanities = Humanities

### ISSUE THREAD

**Issue by GabyKuster** [dasch-swiss/knora-app#131]
Homepage: Link part:
Data and Service Center for humanities (DaSCH): humanities should be written with a capital H

**To Reproduce Steps to reproduce the behavior:**

**OPTIONAL: Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem (drag-and-drop the image directly here).

**Desktop (please complete the following information):**
* OS: Windows 10 Pro N, 1903 - 18362.418
* Browser Google Chrome, 78.0.3904.87

* Version Knora App, 1.6.2

**Additional context**

**Comment by flavens** [comment]
Rita
![image](https://user-images.githubusercontent.com/29532462/68580137-041ec980-0476-11ea-81ac-0b75fa7bfa0e.png)
