### ISSUE TITLE
Contact button should be general, according to issue

### ISSUE THREAD

**Issue by GabyKuster** [dasch-swiss/knora-app#132]
Homepage: Button please contact us: THis should be a link to a general email, or possibly 2 (Basel, Lausanne...) with an explanation whom to contact in what case.

With the link to pictures of the whole team, people have no idea whom to contact in what case. If you really want to show the team, do it somewhere else without direct links to their mailboxes pls)

**To Reproduce Steps to reproduce the behavior:**

**OPTIONAL: Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem (drag-and-drop the image directly here).

**Desktop (please complete the following information):**
* OS: Windows 10 Pro N, 1903 - 18362.418
* Browser Google Chrome, 78.0.3904.87

* Version Knora App, 1.6.2

**Additional context**

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-293](https://dasch.myjetbrains.com/youtrack/issue/DSP-293)
