### ISSUE TITLE
Homepage: Links should open in new Window

### ISSUE THREAD

**Issue by GabyKuster** [dasch-swiss/knora-app#133]
on the very bottom of the homepage, there are 3 links (dasch-swiss githup, twitter...).
They should open a new page when klicked instead of overwriting the Knora-App site.

More links with the same issue are to the very left of the above mentioned links (Knora, Swiss Academy...)

**To Reproduce Steps to reproduce the behavior:**

**OPTIONAL: Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem (drag-and-drop the image directly here).

**Desktop (please complete the following information):**
* OS: Windows 10 Pro N, 1903 - 18362.418
* Browser Google Chrome, 78.0.3904.87

* Version Knora App, 1.6.2

**Additional context**

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-295](https://dasch.myjetbrains.com/youtrack/issue/DSP-295)
