### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by GabyKuster** [dasch-swiss/knora-app#134]
Homepage, without login
After checking the page content
I selected the project Anything
wrote term "test"
search button

=> Error Message, see image

I tried with other projects, only Anything seems to have this problem

**Desktop (please complete the following information):**
* OS: Windows 10 Pro N, 1903 - 18362.418
* Browser Google Chrome, 78.0.3904.87

* Version Knora App, 1.6.2

**Additional context**
![image](https://user-images.githubusercontent.com/56250095/68280736-6e023200-0076-11ea-93a8-b02b61a45bbb.png)

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-304](https://dasch.myjetbrains.com/youtrack/issue/DSP-304)
