### ISSUE TITLE
Empty search leads to error

### ISSUE THREAD

**Issue by GabyKuster** [dasch-swiss/knora-app#135]
Search without login
I select a project (tested with Anything and Images)
leave search window empty
search
long waiting while knora app is searching
then error is displayed (see image) 
please note, the mentioned link is always different

![image](https://user-images.githubusercontent.com/56250095/68281522-2381b500-0078-11ea-97b4-f8aff73cb7dc.png)

**Desktop (please complete the following information):**
* OS: Windows 10 Pro N, 1903 - 18362.418
* Browser Google Chrome, 78.0.3904.87

* Version Knora App, 1.6.2

**Additional context**

**Comment by flavens** [comment]
this behaviour cannot be reproduced in the new versions of Knora-App (now DSP-APP)
