### ISSUE TITLE
Search results title and search button problem

### ISSUE THREAD

**Issue by GabyKuster** [dasch-swiss/knora-app#136]
When I search for an item I get a list of results
The only indication about the search parameters is the still filled in search field itself

My problem was, that sometimes I search for something new after a search, and the search button itself does not react on first clicking, because it is still active with closing the field with the search item. Then I am never sure, if the results belong to the previous or the actual search.

I would wish for 2 adaptations:
- please add a title row above the  search results with the search terms for the results
- please make the search button technically independent of the search term field so they dont interact

**OPTIONAL: Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem (drag-and-drop the image directly here).

**Desktop (please complete the following information):**
* OS: Windows 10 Pro N, 1903 - 18362.418
* Browser Google Chrome, 78.0.3904.87

* Version Knora App, 1.6.2

**Additional context**

**Comment by GabyKuster** [comment]
The same problem I have with advanced search: When I navigate e.g. to the help page and back: The results are still displayed, but the search parameters are nowhere to be found again. If written as plain text as a title, this would help a lot.

**Comment by GabyKuster** [comment]
Same problem with expert search: Titel with general Information to the search itself should be visible

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-310](https://dasch.myjetbrains.com/youtrack/issue/DSP-310)
