### ISSUE TITLE
Text: "Not supported ReadTextValueAsHtml"

### ISSUE THREAD

**Issue by GabyKuster** [dasch-swiss/knora-app#137]
See link: https://app2.test.dasch.swiss/resource/http%253A%252F%252Frdfh.ch%252F0801%252Fi5C2pRMOQbKXyaaLoe4C3A

What does "Title: Not supported ReadTextValueAsHtml" mean?

**Screenshots**
If applicable, add screenshots to help explain your problem (drag-and-drop the image directly here).
![image](https://user-images.githubusercontent.com/56250095/68282997-ff73a300-007a-11ea-84fb-787bf8cc7be5.png)

**Desktop (please complete the following information):**
* OS: Windows 10 Pro N, 1903 - 18362.418
* Browser Google Chrome, 78.0.3904.87

* Version Knora App, 1.6.2

**Additional context**

**Comment by gautschr** [comment]
Same here!

See link:
https://app2.test.dasch.swiss/resource/http%253A%252F%252Frdfh.ch%252F0801%252FfnjgSAZiTmKCp4p7jAOgJg 

for “Text” appears “Not supported ReadTextValueAsHtml”

OS: MacOS Catalina 10.15.1
Browser Safari 13.0.3
Version Knora App, 1.6.2

**Comment by flavens** [comment]
this issue has already been resolved: https://dasch.myjetbrains.com/youtrack/issue/DSP-91
