### ISSUE TITLE
Link leads to empty page

### ISSUE THREAD

**Issue by GabyKuster** [dasch-swiss/knora-app#138]
Link: https://app2.test.dasch.swiss/resource/http%253A%252F%252Frdfh.ch%252F0803%252F5e77e98d2603

when I click (Links: Lateinische Übersetzung) I get an empty page, see screenshot.

![image](https://user-images.githubusercontent.com/56250095/68283503-f20ae880-007b-11ea-8118-59be3b652f81.png)

**Desktop (please complete the following information):**
* OS: Windows 10 Pro N, 1903 - 18362.418
* Browser Google Chrome, 78.0.3904.87

* Version Knora App, 1.6.2

**Additional context**

**Comment by flavens** [comment]
@kilchenmann this situation has happened due to missing data, hasn't it? should we keep this issue to handle the potential case (add warning message for instance)? or it will never happened on production?

**Comment by kilchenmann** [comment]
@flavens Yes it's an issue in the data and has nothing to do the app design directly. But in this case, it would be probably nice to display something like "empty object" or "This resource doesn't contain any data (yet)". A kind of descriptive message. Additional we can list the users of the project or the institute to contact them. This would be a nice feature, but at the moment we don't have all necessary information in the project and I don't know about the privacy rules 😉

**Comment by kilchenmann** [comment]
...but in the new resource viewer, we will link to the project, where all necessary information should be available. But a "empty resource" message would be nice.

**Comment by flavens** [comment]
@kilchenmann yes, at least a message should be displayed.
Regarding the listing of project members, only the project admin should be contacted. But this is another feature..

**Comment by kilchenmann** [comment]
Yes, exactly:

> this is another feature..

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-307](https://dasch.myjetbrains.com/youtrack/issue/DSP-307)
