### ISSUE TITLE
Advanced Search: finding a name

### ISSUE THREAD

**Issue by GabyKuster** [dasch-swiss/knora-app#139]
Advanced search, not logged in:

I try to find an author whose name is like "Peter" but I do not remember the full name in the BEOL Project (see also image)
Unfortunately there is no "is like" or similar operation offered, so I try to search with "is equal to".
Unfortunatley again, I cannot enter "Peter" but instead I get a long list of names containing "Peter" to select from.
So I select one of the names, as I imagine, the selection I receive are authors fitting my search
Instead when I actually do this, I get the message "Sorry, but we couldnt find any results matching your search"

As it looks like: To actually find an author containing that name, I would have to try each of the offered names individually. This makes no sense

**Screenshots**
![image](https://user-images.githubusercontent.com/56250095/68286190-f4bc0c80-0080-11ea-94d8-cff55878b4d7.png)

**Desktop (please complete the following information):**
* OS: Windows 10 Pro N, 1903 - 18362.418
* Browser Google Chrome, 78.0.3904.87

* Version Knora App, 1.6.2

**Additional context**

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-305](https://dasch.myjetbrains.com/youtrack/issue/DSP-305)
