### ISSUE TITLE
Homepage : external links are not easy to spot

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#140]
**Describe the bug**
I find the link to external websites are not very easy to spot, unless you mouse over and look at the bottom left corner of the screen where the URL where the image or text redirects is displayed.

**To Reproduce Steps to reproduce the behavior:**

**OPTIONAL: Expected behavior**
Maybe underline when a text that is an hyperlink?

**Screenshots**
If applicable, add screenshots to help explain your problem (drag-and-drop the image directly here).

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G103), French
 - Browser Firefox 
 - Version 70.01.1

**Additional context**

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-297](https://dasch.myjetbrains.com/youtrack/issue/DSP-297)
