### ISSUE TITLE
Homepage : make the name of the app more visible

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#141]
**Describe the bug**
If Knora-app is going to be the name of Knora GUI, then this name should be displayed in a more prominent way. Currently it only appears on the left bottom corner.

**To Reproduce Steps to reproduce the behavior:**

**OPTIONAL: Expected behavior**
Maybe "**Knora app** is the generic web application of the Data and Service Center for Humanities DaSCH. It's the user interface research layer of Knora..."

**Screenshots**
If applicable, add screenshots to help explain your problem (drag-and-drop the image directly here).

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G103), French
 - Browser Firefox 
 - Version 70.01.1

**Additional context**

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-298](https://dasch.myjetbrains.com/youtrack/issue/DSP-298)
