### ISSUE TITLE
Advanced Search: Why cant i find this result?

### ISSUE THREAD

**Issue by GabyKuster** [dasch-swiss/knora-app#142]
Advanced Search: Not logged in.
See also Image

I selected the Ontology: Musikalisches Lexikon der Schweiz, Resource: Artikel, Properties: In Lexikon
When I select the operator "exists" lots of results are found.
When I try the same with the operator "is equal to" the surch button stays inactive, even when I choose a parameter (here 11) that is displayed in the last results 

See picture: there is an article 5267 in Lexikon 11 from the earlier search still displayed, but I cannot search for this Lexikon with "is equal to", the search button stays inactive.

![image](https://user-images.githubusercontent.com/56250095/68289758-07d1db00-0087-11ea-84a3-9c913ee32e17.png)

**Desktop (please complete the following information):**
* OS: Windows 10 Pro N, 1903 - 18362.418
* Browser Google Chrome, 78.0.3904.87

* Version Knora App, 1.6.2

**Additional context**

**Comment by flavens** [comment]
@kilchenmann in this case, do you think it will be enough to explain the difference between operators in the documentation or a tooltip? because I suppose that lucene or graphDB does not find the same results with these operators, which are similar to a non-IT user

**Comment by kilchenmann** [comment]
@flavens The issue here is that the property "in lexicon" is a resource pointer and must therefore be selected exactly. The advanced search always assumes that you know the ontology. But it is also not completely self-explanatory solved so far.
I suggest to explain the operators in the documentation but why not adding a little help icon (?) which opens a bigger box with a list of all operators and a short description behind.

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-306](https://dasch.myjetbrains.com/youtrack/issue/DSP-306)

**Comment by mrivoal** [comment]
Hello :-) Sorry to sneak in. But the wording of comparison operators could also be more self-explanatory, right? If so, I think the wording could probably be discussed with users.

**Comment by kilchenmann** [comment]
@mrivoal Feel free to make a suggestion for the following operator values:
- contains
- is like
- equals to
- exists

And in case of a date value with 
- before
- after

Btw. We try to use the same names that Apple's macOS offers in search filter:
![Screen Shot 2020-05-29 at 10 48 17](https://user-images.githubusercontent.com/4253580/83240657-00e0f600-a19a-11ea-8a9f-3b36b0b7bfac.png)

Or we can describe as Google does in their advanced search:
![Screen Shot 2020-05-29 at 10 52 05](https://user-images.githubusercontent.com/4253580/83241079-9aa8a300-a19a-11ea-84a7-36be24bf2b70.png)

**Comment by flavens** [comment]
@kilchenmann @mrivoal please, continue the discussion in the YouTrack issue [DSP-306](https://dasch.myjetbrains.com/youtrack/issue/DSP-306)

**Comment by kilchenmann** [comment]
@flavens I'm sorry. I thought @mrivoal doesn't have access to YouTrack. My fault. I added my comment there already 😉 We can keep this issue closed.
