### ISSUE TITLE
Homepage: some statements are not (yet) true

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#143]
**Describe the bug**
The statement that you can upload taped interviews and any kind of media is not true yet. Currently, Knora (or rather Sipi) only handle images and very soon it will handle PDFs but as long as the PDFs are not checked within Knora's framework (validated, well formed, etc. against PDF/A format, for example), I don't think that we should encourage people to upload files other than images.

**To Reproduce Steps to reproduce the behavior:**

**OPTIONAL: Expected behavior**
Maybe keep this statement for latter and be more realistic with Knora (and Knora-app)'s current features?

**Screenshots**
If applicable, add screenshots to help explain your problem (drag-and-drop the image directly here).

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G103), French
 - Browser Firefox 
 - Version 70.01.1

**Additional context**

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-303](https://dasch.myjetbrains.com/youtrack/issue/DSP-303)
