### ISSUE TITLE
Direct linkt to "help" please

### ISSUE THREAD

**Issue by GabyKuster** [dasch-swiss/knora-app#144]
Advanced Search, not logged in.

I was trying to do a search and was not sure about how to use the parameters.
So I clicked the "help" button.
This did not open the user-guide-help-site but I ended up in the general information page.
Now I had to read each seperate information box in order to find out, where I actually get help for my problem in the configuration of  a search (within the Knora app search)

Please, please add a direct help button which leads me to the user Guide and put all the other information that somehow concern Knora and Knora app in general somewhere else.

**Screenshots**
If applicable, add screenshots to help explain your problem (drag-and-drop the image directly here).

**Desktop (please complete the following information):**
* OS: Windows 10 Pro N, 1903 - 18362.418
* Browser Google Chrome, 78.0.3904.87

* Version Knora App, 1.6.2

**Additional context**

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-301](https://dasch.myjetbrains.com/youtrack/issue/DSP-301)
