### ISSUE TITLE
Advanced Search: Project resp. Ontology name is not displayed in results

### ISSUE THREAD

**Issue by GabyKuster** [dasch-swiss/knora-app#145]
Advanced search, not logged in

Neither the individual result records as a list, nor as a grid display the name of the project resp. ontology they belong to.
As the advanced search window is empty when navigating back, this is a necessity, as otherwise there is no indication to which project these results belong to.

**OPTIONAL: Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem (drag-and-drop the image directly here).

**Desktop (please complete the following information):**
* OS: Windows 10 Pro N, 1903 - 18362.418
* Browser Google Chrome, 78.0.3904.87

* Version Knora App, 1.6.2

**Additional context**

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-310](https://dasch.myjetbrains.com/youtrack/issue/DSP-310)
