### ISSUE TITLE
Homepage : database is not mentioned anywhere

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#146]
**Describe the bug**
Homepage : database is not mentionned anywhere but this is why Knora was designed. It is also what makes it so special.
Qualitative data is way to vague in my opinion if we want to target a humanities audience.

**To Reproduce Steps to reproduce the behavior:**

**OPTIONAL: Expected behavior**
Databases should be mentioned somewhere. 
Maybe: "Search for relationships between text, metadata, annotations, markup, links, and more *in your database*?"
Or "You define your data model *for your database*, and Knora ensures that your data is consistent with it." ?
Or even : "The tool is designed to work with qualitative data, *digital collections and databases*."

**Screenshots**
If applicable, add screenshots to help explain your problem (drag-and-drop the image directly here).

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G103), French
 - Browser Firefox 
 - Version 70.01.1

**Additional context**

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-308](https://dasch.myjetbrains.com/youtrack/issue/DSP-308)
