### ISSUE TITLE
Search operator description?

### ISSUE THREAD

**Issue by GabyKuster** [dasch-swiss/knora-app#147]
Advanced Searched, not logged in

I tried to find out, how the operator "is equal to" works. Where would I find information and help?
I actually wondered, why I could not find a result, when I was looking for letters with the language "german". It seems to be, that "the equals to" operator is case senstitive. 

One question is, if this makes sense, another, where I can find this information.

**Screenshots**
If applicable, add screenshots to help explain your problem (drag-and-drop the image directly here).

**Desktop (please complete the following information):**
* OS: Windows 10 Pro N, 1903 - 18362.418
* Browser Google Chrome, 78.0.3904.87

* Version Knora App, 1.6.2

**Additional context**

**Comment by mrivoal** [comment]
The differences between the **text operators**
- is like
- matches
- is equal to
is not easy to figure out. I am not even sure myself what they actually mean and they date back to Salsah!
Documentation would help but I also wonder if better wording cannot be found, with users' help.

E.g. for **text comparison operators**
- is like = contains?
- matches = contains?
- is equal to = contains exactly?
- is not equal to = does not contain ?

For **date comparison operators**, the wording could be also adapted.
- is equal to 
- is not equal to = is different from ?
- is less than = before
- is greater than = after
- is less than equals to = equals or before?
- is greater than equals to = equals or after?

**Comment by mrivoal** [comment]
And I think tooltips embedded in the application would be my best choice (compared to a link to an external documentation).

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-306](https://dasch.myjetbrains.com/youtrack/issue/DSP-306)
