### ISSUE TITLE
Advanced Search: sort order in dropdown list

### ISSUE THREAD

**Issue by GabyKuster** [dasch-swiss/knora-app#149]
Advanced search, not logged in

I want to search all letters by the author "is equal to" Leonhard Euler.
As already mentioned in #139 I cannot add a text when I select "is equal to" but have to select from a list.
Unfortunately the entries in the offered selection seem not to be sorted in any kind, which makes it very hard to find the correct entry, especially when the list is long. 
I would suggest to have it sorted by last name and then add the first names. e.g. 
Euler, Charlotte; 
Euler, Leonhard... 
etc.

**OPTIONAL: Expected behavior**

![image](https://user-images.githubusercontent.com/56250095/68292286-d576ac80-008b-11ea-88e3-4a78b227d726.png)

**Desktop (please complete the following information):**
* OS: Windows 10 Pro N, 1903 - 18362.418
* Browser Google Chrome, 78.0.3904.87

* Version Knora App, 1.6.2

**Additional context**

**Comment by flavens** [comment]
@tobiasschweizer referring to Gaby's comment and screen shot above > how does the resource list of Author's name (in the example) sort out? is there any sorting?

**Comment by tobiasschweizer** [comment]
It depends on the prop's cardinality if it can be used as a sorting criterion or not. If the cardinality is 1 or max 1, there should be a checkbox "sort criterion" that the user can activate:

https://github.com/dasch-swiss/knora-ui/blob/2986f4e048daa28e5eb23b4920b4dea6cebebf77/projects/knora/search/src/lib/extended-search/select-property/select-property.component.ts#L104-L131

The reason for this is that you cannot order search results by a property that occurs several times on a resource. However, this is still an open TODO in Gravsearch:

https://github.com/dasch-swiss/knora-api/blob/bd08f2c734c59b63960a05e8a0277acc7b58f5e9/webapi/src/main/scala/org/knora/webapi/responders/v2/SearchResponderV2.scala#L368-L369

**Comment by flavens** [comment]
@tobiasschweizer ok thanks. And about the list of value in the advanced form, is there any sorting of the names here?

**Comment by tobiasschweizer** [comment]
> And about the list of values in the advanced form, is there any sorting of the names here?

I don't understand what you mean by "list of values in the advanced form"

**Comment by flavens** [comment]
the dropdown list of values for the property "Author" in the advanced search (see issue description):
<img width="358" alt="Screenshot 2020-06-02 at 09 44 18" src="https://user-images.githubusercontent.com/29532462/83493832-a99e9680-a4b5-11ea-89cc-f195b480f5a7.png">

**Comment by tobiasschweizer** [comment]
This is what https://docs.knora.org/paradox/03-apis/api-v2/reading-and-searching-resources.html#search-for-a-resource-by-its-rdfs-label returns. 

I think Knora sorts by resource IRI so the the order is deterministic:

https://github.com/dasch-swiss/knora-api/blob/develop/webapi/src/main/twirl/queries/sparql/v2/searchResourceByLabelSubQuerySelectGraphDB.scala.txt

I guess this could be made more flexible (optional param in URL) so the `rdfs:label` is used for sorting. But then it would be sorted by the whole `rdfs:label`, sot just by what the user searches for.

**Comment by flavens** [comment]
@tobiasschweizer thanks for the explanation. It should be more flexible because users get confused in front of a list that is not order by alphabetical order.

**Comment by tobiasschweizer** [comment]
> It should be more flexible because users get confused in front of a list that is not order by alphabetical order.

Yes, but probably the user could also get confused when searching for a person's family name like "Euler" and then getting a list sorted by the whole `rdfs:label` beginning with the first name "Leonhard Euler". Maybe there is some Lucene syntax features that could be used.

**Comment by flavens** [comment]
> Yes, but probably the user could also get confused when searching for a person's family name like "Euler" and then getting a list sorted by the whole `rdfs:label` beginning with the first name "Leonhard Euler". Maybe there is some Lucene syntax features that could be used.

As Gaby suggested in her comment above, it makes more sense in this case to order the value list by last name. But the ordering depends on the value list, it is really specific. We can discuss that another time, it is not an urgent priority.

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-315](https://dasch.myjetbrains.com/youtrack/issue/DSP-315)
