### ISSUE TITLE
The project selection window remains open when you use the full-text search

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#150]
**Describe the bug**
As unregistered user, when I want to use the full-text search within a project, the window where I selected the project remains opened even though I am typing in the full-text search area.

**To Reproduce Steps to reproduce the behavior:**
1. Go to 'Filter by project'
2. Click on 'Beol'
3. Go to the full-text search area
4. See that the project selection window remains opened

**OPTIONAL: Expected behavior**
Once I have selected the project, the window should close automatically.

**Screenshots**
![Capture d’écran 2019-11-06 à 11 58 34](https://user-images.githubusercontent.com/17294309/68292745-c8a68880-008c-11ea-86d6-a5e5eda8b630.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G103), French
 - Browser Firefox 
 - Version 70.01.1

**Additional context**

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-323](https://dasch.myjetbrains.com/youtrack/issue/DSP-323)
