### ISSUE TITLE
Removing a search criteria e.g. property

### ISSUE THREAD

**Issue by GabyKuster** [dasch-swiss/knora-app#151]
*Advanced Search, not logged in

I created a long search with several selection properties.
There seems to be a limit in criterias (see also image)
Now I decide, that the first of the properties is not so important and I wish to remove it from my list (in this example im picture the property "Color - exists).

There seems to be no possibility to remove that property individually but I have to remove all others afterwards in the list as well.

![image](https://user-images.githubusercontent.com/56250095/68293465-4cad4000-008e-11ea-826a-e9d512b2b861.png)

**Desktop (please complete the following information):**
* OS: Windows 10 Pro N, 1903 - 18362.418
* Browser Google Chrome, 78.0.3904.87

* Version Knora App, 1.6.2

**Comment by mrivoal** [comment]
I agree with this.

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-324](https://dasch.myjetbrains.com/youtrack/issue/DSP-324)
