### ISSUE TITLE
Advanced search : using Firefox, you have to scroll down a lot to see search results

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#152]
**Describe the bug**
Using the advanced search feature on Firefox,the search results are displayed at the very bottom of the web page after a lot of blank space that you have to scroll down.
Happens both without and after login.

**To Reproduce Steps to reproduce the behavior:**
1. Open Firefox.
2. Go to 'Advanced search'
3. Click on 'The anything ontology'
4. Select 'Thing' as resource class
5. Click on 'Search'
6. See error

**OPTIONAL: Expected behavior**

**Screenshots**
![Capture d’écran 2019-11-06 à 12 12 07](https://user-images.githubusercontent.com/17294309/68293653-b0376d80-008e-11ea-92af-a46b5ad7ec6a.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G103), French
 - Browser Firefox 
 - Version 70.01.1

**Additional context**

**Comment by flavens** [comment]
this issue cannot be reproduced, the search module and the search results components will be refactored soon so this blank space will be fixed anyway
