### ISSUE TITLE
Full text search to advanced search : previous full text search criteria shouldn't be displayed anymore

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#153]
**Describe the bug**
When moving from full text search to advanced search, the full text search criteria previously entered is still displayed.
Happens both without and after login.

**To Reproduce Steps to reproduce the behavior:**
1. Go to 'Filter by project'
2. Select 'Anything'
3. Go to the full-text search area
4. Enter 'Sierra'
5. Click on 'Search'
6. Select the 'Advanced search' tab
7. Begin to enter any advanced search query
8. See that the full text search criteria is still displayed

**OPTIONAL: Expected behavior**
The previous full-text search criteria should be deleted.

**Screenshots**

![Capture d’écran 2019-11-06 à 12 22 56](https://user-images.githubusercontent.com/17294309/68294338-31dbcb00-0090-11ea-9d58-a323b0dec58b.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G103), French
 - Browser Firefox 
 - Version 70.01.1

**Additional context**

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-325](https://dasch.myjetbrains.com/youtrack/issue/DSP-325)
