### ISSUE TITLE
System administrator : default opening page should be "system"

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#154]
**Describe the bug**
I think the default page displayed once a system admin has logged in should probably by the view he will get by selecting "System" under the user menu.

**To Reproduce Steps to reproduce the behavior:**

**OPTIONAL: Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem (drag-and-drop the image directly here).

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G103), French
 - Browser Firefox 
 - Version 70.01.1

**Additional context**

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-326](https://dasch.myjetbrains.com/youtrack/issue/DSP-326)
