### ISSUE TITLE
empty Expert search "leads to failure response"

### ISSUE THREAD

**Issue by GabyKuster** [dasch-swiss/knora-app#155]
Expert search, not logged in

I clear the expert search window completely
Click button "Search"
Message "Http failure response for https://api.test.dasch.swiss/v2/searchextended/count: 400 OK" is displayed.

In this case there should be a clear message displayed, why no search is possible. E.g. Please add valid gravesearch statements, maybe with a link to gravesearch. 

**Screenshots**
![image](https://user-images.githubusercontent.com/56250095/68298319-54bead00-0099-11ea-8fcb-dd3c0922cd4a.png)

**Desktop (please complete the following information):**
* OS: Windows 10 Pro N, 1903 - 18362.418
* Browser Google Chrome, 78.0.3904.87

* Version Knora App, 1.6.2

**Comment by GabyKuster** [comment]
If I add simple text, this message is displayed : Http failure response for https://api.test.dasch.swiss/v2/searchextended: 400 OK is displayed.

In any case, there should be always be an error handler who gives a response, that non-software-people can understand

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-304](https://dasch.myjetbrains.com/youtrack/issue/DSP-304)
