### ISSUE TITLE
Expert Search: Comparing search results

### ISSUE THREAD

**Issue by GabyKuster** [dasch-swiss/knora-app#156]
Expert Search, not logged in

I use the default search in Expert Search
I get the result "Das Narrenschiff (lat.) twice with exactly the same information (see image).
Only when I open them individually, I can see, that these are 2 different books.

Unfortunately I can only open the one or the other, but never both together, not even in different windows. This way it is hard to compare the two records.

Is there anything planned for this use case?

**Screenshots**
![image](https://user-images.githubusercontent.com/56250095/68299231-98b2b180-009b-11ea-9f9c-d283e7c84610.png)

**Desktop (please complete the following information):**
* OS: Windows 10 Pro N, 1903 - 18362.418
* Browser Google Chrome, 78.0.3904.87

* Version Knora App, 1.6.2

**Comment by flavens** [comment]
@GabyKuster yes, a comparison viewer is planned to open side by side 2 or more resources

**Comment by flavens** [comment]
this issue has been moved on YouTrack: [DSP-321](https://dasch.myjetbrains.com/youtrack/issue/DSP-321)
