### ISSUE TITLE
Login: Username case sensitive?

### ISSUE THREAD

**Issue by GabyKuster** [dasch-swiss/knora-app#157]
Login window:

When I login as a project member I found, that the Username is case sensitive.
Is this how it should be?

**Desktop (please complete the following information):**
* OS: Windows 10 Pro N, 1903 - 18362.418
* Browser Google Chrome, 78.0.3904.87

* Version Knora App, 1.6.2

**Comment by flavens** [comment]
@kilchenmann indeed the username field is case sensitive > should it stay case sensitive? I do not know what is the best practice about this case

**Comment by kilchenmann** [comment]
@flavens The case sensitivity of the login form is determined by Knora. I don't know if we can do in another way. What do @subotic and @benjamingeer think?

**Comment by benjamingeer** [comment]
I think it wouldn't be good to have two different users called `hermann` and `hermanN`.

This would be easy to change in Knora.

**Comment by kilchenmann** [comment]
> This would be easy to change in Knora.

That would be great if you can change it. Thank you @benjamingeer

**Comment by subotic** [comment]
I would suggest to keep the case sensitivity, but to broaden the uniqueness of the username to include any case combinations.

**Comment by subotic** [comment]
The case sensitivity would need to be mentioned in the gui somewhere and maybe even caps lock detected, etc.

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-317](https://dasch.myjetbrains.com/youtrack/issue/DSP-317)
If there are other comments, please write them in the comment section of the YT issue.
