### ISSUE TITLE
Login Process: "Welcome" Window missing

### ISSUE THREAD

**Issue by GabyKuster** [dasch-swiss/knora-app#158]
Login with a Project user
=> I expect something like a welcome window or similar. But instead I am still in the same search result window from before. There is no idication with what creditals I am logged in. Only when I click on the top left icon, I can with what name I am loged in.

**OPTIONAL: Expected behavior**

![image](https://user-images.githubusercontent.com/56250095/68300342-df091000-009d-11ea-9b8c-ab036d126fa1.png)

**Desktop (please complete the following information):**
* OS: Windows 10 Pro N, 1903 - 18362.418
* Browser Google Chrome, 78.0.3904.87

* Version Knora App, 1.6.2

**Comment by flavens** [comment]
@kilchenmann would you consider to change this behaviour in the future or keep it as it is?

**Comment by kilchenmann** [comment]
No. If you log in on a specific route, you will return to the same page after logging in. This is common practice for many applications today. What we can do is show a small banner at the top: "Successful login".

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-331](https://dasch.myjetbrains.com/youtrack/issue/DSP-331)
