### ISSUE TITLE
Admin Login: Default sort order of projects

### ISSUE THREAD

**Issue by GabyKuster** [dasch-swiss/knora-app#159]
Login as a system administrator:

1. List of projects is displayed
2. Default sort oder seems to be "sorted by short name"
3. As most prominent of each recort is "Project name", I expect that the default sort oders is according to Project name.

**OPTIONAL: Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem (drag-and-drop the image directly here).

**Desktop (please complete the following information):**
* OS: Windows 10 Pro N, 1903 - 18362.418
* Browser Google Chrome, 78.0.3904.87

* Version Knora App, 1.6.2

**Additional context**

**Comment by GabyKuster** [comment]
When I navigate to another page in the System administration part and back to Projects overview, the sort order I selected is RESET!
THis should not happen please.

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-329](https://dasch.myjetbrains.com/youtrack/issue/DSP-329)
