### ISSUE TITLE
System administrator : project creation form tooltips could be more helpful

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#160]
**Describe the bug**
The project creation form could state for each element the expected format.
Currently, unless you type something wrong, you don't know the expected format (for short code, for example).

For **keywords**, I didn't know what kind of format is expected. I thought it would be a list of keywords with a separator (but which one?). That is why it took me a while to realise that I had to press enter after each keyword so that it is recorded separately.

**To Reproduce Steps to reproduce the behavior:**

**OPTIONAL: Expected behavior**
Maybe examples of the expected format in grey could be displayed in the entry field and the user overwrite them when he enters his own data.

For **shortname**, the max number of characters allowed should be stated. I think diacritical sign should also probably be forbidden and it should be made clear.

Also, I had a message `Short name shouldn't start with a number; Spaces are not allowed.` when the first letter of the short-code was `é`

**Screenshots**

![Capture d’écran 2019-11-06 à 14 34 26](https://user-images.githubusercontent.com/17294309/68302691-ccdda080-00a2-11ea-8627-edca4a4f5a64.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G103), French
 - Browser Firefox 
 - Version 70.01.1

**Additional context**

**Comment by GabyKuster** [comment]
Same for me.
Addition: There should be any information what the difference between Kurzcode (Shortcode) and Abkürzung (Short name) is. To me they seem to mean the same: For one numbers are allowed but not for the other.

**Comment by flavens** [comment]
this issue has been moved to YouTrack :[DSP-332](https://dasch.myjetbrains.com/youtrack/issue/DSP-332)
