### ISSUE TITLE
System admin: Navigation and menus not very self-explaining, sometimes pretty confusing

### ISSUE THREAD

**Issue by GabyKuster** [dasch-swiss/knora-app#161]
As I prepared the tests, I struggled through the menus numberous times, always searching for the same parts of the system admin user interface:

A system admin has 2 main tasks: Manage Users and manage Projects.
The navigation to both of these tasks should be very prominently on the Welcome page.

The menu to the **user administration** is at the moment in the personal button (round button on the top right) in a menu point "System". I would never look there for the User management. When I click there, the windows displays a new view that can be toggled between "All projects" and "All Users". I think this should be, how the login welcome page should look like. (see image).

In the "All User" part, I can add new users and new System admins and add users to a project. But I cannot set the role "project admisitrator" which is very confusing. I would suggest to have 3 options on this page instead of hiding the project management role setting in the individual project page. This way the main administration interface would allow to toggle through: "**All Projects", "All Users" and "Project - User Collaboration"**. This new toggle option is menat as the main position, where all Project - User connections (Project admin and project member) are set.

**Screenshots**
![image](https://user-images.githubusercontent.com/56250095/68301916-43799e80-00a1-11ea-8ede-08e550ce7f21.png)

**Desktop (please complete the following information):**
* OS: Windows 10 Pro N, 1903 - 18362.418
* Browser Google Chrome, 78.0.3904.87

* Version Knora App, 1.6.2

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-328](https://dasch.myjetbrains.com/youtrack/issue/DSP-328)
