### ISSUE TITLE
Member user : the first page displayed after login is the one I was reading as system admin and member is unauthorized 

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#162]
**Describe the bug**
As a system admin, I created a member and attached it to a project under the collaboration tab. Then I logged out and logged in again with the member profil. The page I landed was the last one I was viewing as system admin (https://app2.test.dasch.swiss/project/785F/collaboration) and, being a member, I wasn't authorized to see it. I ended up with the error in screenshot.

I guess it could be an issue with cookies? 

**To Reproduce Steps to reproduce the behavior:**

**OPTIONAL: Expected behavior**

**Screenshots**
![Capture d’écran 2019-11-06 à 14 51 49](https://user-images.githubusercontent.com/17294309/68304527-37dca680-00a6-11ea-9d60-3bcf68cf7458.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G103), French
 - Browser Firefox 
 - Version 70.01.1

**Additional context**

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-336](https://dasch.myjetbrains.com/youtrack/issue/DSP-336)
