### ISSUE TITLE
Updating Project information, User information

### ISSUE THREAD

**Issue by GabyKuster** [dasch-swiss/knora-app#163]
Login as a system administrator

I tried to update the **shortcode** and **short name** of the project and found out, that was not possible. I also found out, that short code and short name seem to be unique identifiers.

In my earlier software life with large projects that was a point we often discussed. The quintesenz was, that unique identifiers have to be invisible system numbers, all other information needs to be adjustable.

The same problem I see the user Information "**email**": Emails change e.g. when researchers move between Institutions, but they cannot be updated in the User Administration which generates extra work.

**OPTIONAL: Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem (drag-and-drop the image directly here).

**Desktop (please complete the following information):**
* OS: Windows 10 Pro N, 1903 - 18362.418
* Browser Google Chrome, 78.0.3904.87

* Version Knora App, 1.6.2

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-338](https://dasch.myjetbrains.com/youtrack/issue/DSP-338)
