### ISSUE TITLE
Add roles to project, workflow unclear

### ISSUE THREAD

**Issue by GabyKuster** [dasch-swiss/knora-app#164]
System admin

I created a project and now I wish to add a role (e.g. Project manager) to the project
see picture: I automatically select the menu next to the project and select "Edit project". 
And then I am lost, as there is no functionality to add a role to the project.

Please see also #161 as a suggestion.

**OPTIONAL: Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/56250095/68305357-d61d3c00-00a7-11ea-9d12-92e9eca79ae9.png)

**Desktop (please complete the following information):**
* OS: Windows 10 Pro N, 1903 - 18362.418
* Browser Google Chrome, 78.0.3904.87

* Version Knora App, 1.6.2

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-339](https://dasch.myjetbrains.com/youtrack/issue/DSP-339)
