### ISSUE TITLE
Wording for mandatory fields

### ISSUE THREAD

**Issue by GabyKuster** [dasch-swiss/knora-app#165]
At many forms with mandatory fields, the requirements are discribed with "the entry should be" like this or that. 
As I found out, they system does not ask that as a suggestion but as a requirement, which needs to be fulfilled.
In this case you should rather write: "the entry **must** be like this or that"

**OPTIONAL: Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem (drag-and-drop the image directly here).

**Desktop (please complete the following information):**
* OS: Windows 10 Pro N, 1903 - 18362.418
* Browser Google Chrome, 78.0.3904.87

* Version Knora App, 1.6.2

**Comment by flavens** [comment]
@kilchenmann do you think there are still form field error messages like "...should be..."? I searched for it, checked the Angular Material but I could not find what Gaby mentioned in this issue.

**Comment by kilchenmann** [comment]
> I could not find what Gaby mentioned in this issue.

Me neither... but probably I misunderstand what she means. We can show sentence like: "Username can't be blank". But I think @SepidehAlassi already worked on error messages [DSP-125](https://dasch.myjetbrains.com/youtrack/issue/DSP-125). Probably we can adapt them for the admin interface?

**Comment by flavens** [comment]
> Me neither... but probably I misunderstand what she means. We can show sentence like: "Username can't be blank". But I think @SepidehAlassi already worked on error messages [DSP-125](https://dasch.myjetbrains.com/youtrack/issue/DSP-125). Probably we can adapt them for the admin interface?

Sepideh improved and added error messages for the value components, part of the resource viewer. We should indeed check and improve these messages for the admin UI.

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-304](https://dasch.myjetbrains.com/youtrack/issue/DSP-304)
