### ISSUE TITLE
Wording: Users - Members

### ISSUE THREAD

**Issue by GabyKuster** [dasch-swiss/knora-app#166]
Loged in as a System admin.

When I open the window "all **_users_**" the table is displayed with the title: 283 **_Members_**.
Please use everywhere the same term for the same content.

**OPTIONAL: Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem (drag-and-drop the image directly here).

**Desktop (please complete the following information):**
* OS: Windows 10 Pro N, 1903 - 18362.418
* Browser Google Chrome, 78.0.3904.87

* Version Knora App, 1.6.2

**Comment by kilchenmann** [comment]
reolved in #218
