### ISSUE TITLE
Archived projects : wording not accurate

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#167]
**Describe the bug**
A system admin can "archive" a project. But I don't think "archive" is the right wording here. What he can so as a system admin is more like "deactivate" a project or set it as "inactive". 

In the future, I can imagine there could be various status for a projects research data and "archived" has a specific meaning (long-term curation) that shouldn't be confused with a project that has been "deactivated".

**To Reproduce Steps to reproduce the behavior:**

**OPTIONAL: Expected behavior**
Replace "archive" with "deactivate". BTW, to remove a project from the "Archived project" list, the wording used is "reactivate". 

**Screenshots**
If applicable, add screenshots to help explain your problem (drag-and-drop the image directly here).

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G103), French
 - Browser Firefox 
 - Version 70.01.1

**Additional context**

**Comment by GabyKuster** [comment]
An addition to this case: 
As a project admin when I click: **Archive** Project this opens a window asking, if i wish to **delete** the project. This wording is missleading.

**Comment by gautschr** [comment]
If I click “Archive project” I’m asked if I want to delete this project. This is definitely not intended if I want to archive an object. There should be a clear distinction between “archived” and deleted”. For the latter a separate button should be made!

**Comment by kilchenmann** [comment]
> "archived" has a specific meaning (long-term curation) that shouldn't be confused with a project that has been "deactivated".

I thought all projects are long-term curated? This is why I named it archived project instead of deactivated. It's in my point of view the same, but archive is nicer than deactivate. But we will change it, if it's wished.

**Comment by mrivoal** [comment]
You are right, for the moment every project in Knora is supposed to be long-term curated. 

But then you don't have to archive a project to have it curated. I thought that what was meant by "archive" here was to deactivate a project or put in in stand by. I can see various reasons for which we will need to be able to (maybe temporarily) deactivate project : some projects are aborted and we will need to deactivate them (I guess that would mean turning their status to `knora-base:status "false"^^xsd:boolean` in `http://www.knora.org/data/admin`)... As a consequence these projects should no longer be accessible to non system admin users.  At least that is the way I see it, but maybe I am wrong?
