### ISSUE TITLE
Searching for Users, Sort Order

### ISSUE THREAD

**Issue by GabyKuster** [dasch-swiss/knora-app#168]
Logged in as a System administrator.
Window "All users"
Displayed are 283 Users according to the list information
I need to find a specific one, I think there should be some kind of search, as there will be lots more soon.

Also: the default sort order seems to be the login name(?) which is often pretty cryptical. I would suggest to use the last name  instead. And please keep a manual sort order during the whole session. Right now it is resorted, as soon as I click on one of the recorts.

**OPTIONAL: Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem (drag-and-drop the image directly here).

**Desktop (please complete the following information):**
* OS: Windows 10 Pro N, 1903 - 18362.418
* Browser Google Chrome, 78.0.3904.87

* Version Knora App, 1.6.2

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-340](https://dasch.myjetbrains.com/youtrack/issue/DSP-340)
