### ISSUE TITLE
Member only of an "archived" project can still log in : correct behavior? 

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#169]
**Describe the bug**
A member of a project that has been archived/deactivated can still log in. I wonder whether it is a correct behavior. If the user was only member of one project and if this project is deactivated, should he still be able to log in? (He couldn't do much but still, I think the question is worth asking)

**To Reproduce Steps to reproduce the behavior:**

**OPTIONAL: Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem (drag-and-drop the image directly here).

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G103), French
 - Browser Firefox 
 - Version 70.01.1

**Additional context**

**Comment by flavens** [comment]
@kilchenmann what do you think?

**Comment by kilchenmann** [comment]
Yes, they can still login, because the project is archived and not the user itself. This is something that probably Knora-Api can handle? 
@flavens Can you create a user story and assign to the backend-developers? Or what do you think?

**Comment by subotic** [comment]
This behaviour seems correct to me.  A "user" is an user of the whole platform.

**Comment by flavens** [comment]
@kilchenmann @subotic if the current behaviour is correct, I will close this issue without creating a YT issue. Is it ok?

**Comment by kilchenmann** [comment]
@flavens I agree to close this issue without moving to YT
