### ISSUE TITLE
New Projects missing in dropdown

### ISSUE THREAD

**Issue by GabyKuster** [dasch-swiss/knora-app#170]
1. - logged in as a System admin
2. - Menu "All users"
3. - Menu to the right of a user / manage project membership
4. - User window is opened
5. - Last point "add user to project"
6. - Dropdown of projects is opened: all the newly created projects are not in dropdown (see image)

 

**OPTIONAL: Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/56250095/68308057-7f663100-00ac-11ea-8479-7a44c26d3f8a.png)

**Desktop (please complete the following information):**
* OS: Windows 10 Pro N, 1903 - 18362.418
* Browser Google Chrome, 78.0.3904.87

* Version Knora App, 1.6.2

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-341](https://dasch.myjetbrains.com/youtrack/issue/DSP-341)
