### ISSUE TITLE
Admin role not displayed in user list of project admin

### ISSUE THREAD

**Issue by GabyKuster** [dasch-swiss/knora-app#171]
1. Loged in as a project admin
2. Menu: project / collaboration
3. All members of the project are displayed but system admin are not visible for their role, they look like ordinary project members (see picture: gaby and marion are system admin).

**OPTIONAL: Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/56250095/68308934-f4863600-00ad-11ea-849a-42704850086d.png)

**Desktop (please complete the following information):**
* OS: Windows 10 Pro N, 1903 - 18362.418
* Browser Google Chrome, 78.0.3904.87

* Version Knora App, 1.6.2

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-342](https://dasch.myjetbrains.com/youtrack/issue/DSP-342)
