### ISSUE TITLE
Clicking on lamp icon several times changes sort order of list

### ISSUE THREAD

**Issue by GabyKuster** [dasch-swiss/knora-app#172]
1. Logged in as a project admin
2. on home page
3. 2 projects are displayed (see image)
4. by clicking several times on the lamp icon (top left corner) the list changes the sort order. ;-)

**OPTIONAL: Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem (drag-and-drop the image directly here).
![image](https://user-images.githubusercontent.com/56250095/68309385-a4f43a00-00ae-11ea-9c95-dc080603ab60.png)

**Desktop (please complete the following information):**
* OS: Windows 10 Pro N, 1903 - 18362.418
* Browser Google Chrome, 78.0.3904.87

* Version Knora App, 1.6.2

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-314](https://dasch.myjetbrains.com/youtrack/issue/DSP-314)
