### ISSUE TITLE
Project admin has specific project activity management needs

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#173]
**Describe the feature**
As a project admin, I will have specific needs. I think project admin will rather rarely administer more than one project so I think the features Knora-app should offer to them should focus on project activity management.

As a project admin, I would like my landing page to display information about the project as it currently does. But I would also like to see a menu (maybe just like the current `project` menu) gathering the members of my projects (I wouldn't want to bother to clic "edit project", then "collaboration") and their groups (in case of custom user groups)

I would also like to be able te review the project's activity globally (see screenshot 1), by members (last edition), by resource class. Screenshot 2 can be inspiring.

**Screenshots**
Screenshot 1:
![Capture d’écran 2019-11-06 à 16 32 35](https://user-images.githubusercontent.com/17294309/68312279-1c2bcd00-00b3-11ea-8919-3b7b6cb2d3b6.png)

Screenshot 2:
![Capture d’écran 2019-11-06 à 16 40 06](https://user-images.githubusercontent.com/17294309/68313261-901aa500-00b4-11ea-9aa0-bfbcb0a9c423.png)

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-326](https://dasch.myjetbrains.com/youtrack/issue/DSP-326)
