### ISSUE TITLE
Wording: delete, deactivate or archive a user?

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#174]
**Describe the bug**
In the user profil, all terms are used.
`Deactivate user account` and when you click on `Deactivate user account` you are asked if you want to *delete* this user.
And once you have accepted, the user is displayed as *archived*.

**To Reproduce Steps to reproduce the behavior:**

**OPTIONAL: Expected behavior**
Normalize the wording.

**Screenshots**
![Capture d’écran 2019-11-06 à 17 11 18](https://user-images.githubusercontent.com/17294309/68315714-78ddb680-00b8-11ea-8ea6-9cb367790fb1.png)

![Capture d’écran 2019-11-06 à 17 15 26](https://user-images.githubusercontent.com/17294309/68316039-0d481900-00b9-11ea-993d-9d76a0b6a9c4.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G103), French
 - Browser Firefox 
 - Version 70.01.1

**Additional context**

**Comment by kilchenmann** [comment]
It's true it wasn't consistent. What speaks against "suspend"? It's more accurate to user profile. I saw the term "suspend" already in a lot applications and for me it was the better choice than deactivate. But okay...

**Comment by mrivoal** [comment]
Suspend is fine to me.

**Comment by kilchenmann** [comment]
resolved in #218
