### ISSUE TITLE
Once a member is deactivated/deleted/archived, shouldn't he be logged out straight away? 

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#175]
**Describe the bug**
After I deactivate my user, if I don't log out, it looks like I am still part of a project, as if I still was an active user.
However, once I logged out, I can no longer log in.

**To Reproduce Steps to reproduce the behavior:**

**OPTIONAL: Expected behavior**
I think a user should be logged out at once when deactivated.

**Screenshots**
![Capture d’écran 2019-11-06 à 17 17 42](https://user-images.githubusercontent.com/17294309/68316225-62842a80-00b9-11ea-8734-4d2e91dcfbe7.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G103), French
 - Browser Firefox 
 - Version 70.01.1

**Additional context**

**Comment by gautschr** [comment]
I agree - I was astonished that I wasn't logged out immediately and could still work until I logged out myself.

OS: macOS Catalina 10.15.1
Browser Safari 13.0.3

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-344](https://dasch.myjetbrains.com/youtrack/issue/DSP-344)
