### ISSUE TITLE
search results displayed as List or Grid

### ISSUE THREAD

**Issue by gautschr** [dasch-swiss/knora-app#176]
**Describe the bug**
If I select “Grid” as display mode and click the “Load more” button, then the results are displayed as list again. This is a bit unexpected.

**To Reproduce**

**Expected behavior**
If I select "Grid" as display option I expect that results are displayed grid-like again after I loaded more results.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.1
 - Browser Safari
 - Version 13.0.3

**Smartphone (please complete the following information):**

**Additional context**

**Comment by flavens** [comment]
this issue has been resolved by changing the "load more" button by a pagination system.
