### ISSUE TITLE
Full text search : user should be able to sort search results by label

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#177]
**Describe the bug**
User should be able to sort search results after a full-text search. 

**To Reproduce Steps to reproduce the behavior:**

**OPTIONAL: Expected behavior**
I know you are planning to filter search results by facets (#111). But if you have a lot of resources, it won't be enough. After, or even before sorting search results by facets, users will still want to sort search results by `rdfs:label`, which is the common property/metadata for all resources classes.

**Screenshots**
If applicable, add screenshots to help explain your problem (drag-and-drop the image directly here).

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G103), French
 - Browser Firefox 
 - Version 70.01.1

**Additional context**

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-342](https://dasch.myjetbrains.com/youtrack/issue/DSP-343)
