### ISSUE TITLE
after logout still on the same page

### ISSUE THREAD

**Issue by gautschr** [dasch-swiss/knora-app#178]
**Describe the bug**
After logout the current page stays visible which may contain information which I'm only allowed to see as e.g. project manager.

**To Reproduce**

**Expected behavior**
I would expect to be directed to the start page after logout.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.1
 - Browser Safari
 - Version 13.0.3

**Smartphone (please complete the following information):**

**Additional context**

**Comment by flavens** [comment]
**similiar comment from Regula:** "when I log out as user and then log back in as project admin, I get back to last search image (in my case the expert search screen full of code), I would expect to be back to the start for a fresh search."

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-336](https://dasch.myjetbrains.com/youtrack/issue/DSP-336)
