### ISSUE TITLE
Text fields using the standard standoff mapping are not rendered correctly

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#179]
**Describe the bug**
In Lumières.Lausanne ontology, several properties use the standard standoff mapping (`salsah-gui:guiElement salsah-gui:Richtext`) and these properties are not rendered correctly in knora app (whereas they are in Salsah 1.5).

**To Reproduce Steps to reproduce the behavior:**
1. In the full text search field, enter  `"Selon le registre paroissial de Moudon"`
2. See the result.

**OPTIONAL: Expected behavior**
I expect richtext properties using the standard standoff mapping to be rendered correctly.

**Screenshots**
In knora app:
![Capture d’écran 2019-11-07 à 14 23 52](https://user-images.githubusercontent.com/17294309/68392539-41c7dd80-016a-11ea-9bce-c13afa53a39d.png)

The same `Note` in Salsah 1.5:
![Capture d’écran 2019-11-07 à 14 24 47](https://user-images.githubusercontent.com/17294309/68392587-602dd900-016a-11ea-9381-019493c7edd3.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G103), French
 - Browser Firefox 
 - Version 70.01.1

**Additional context**

**Comment by flavens** [comment]
2 issues on YouTrack mention this problem: [DSP-279](https://dasch.myjetbrains.com/youtrack/issue/DSP-279) + [DSP-47](https://dasch.myjetbrains.com/youtrack/issue/DSP-47)
this issue has been mentioned in the comment section of both issues
