### ISSUE TITLE
Advanced search : user should be able to search using the rdfs:label property of a resource

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#180]
**Describe the bug**
Using the advanced search, user should be able to use the property/metadata rdfs:label of a resource as a search criteria.

Is linked to [knora-api issue #802](https://github.com/dasch-swiss/knora-api/issues/802) and to [knora-ui issue 302](https://github.com/dasch-swiss/knora-ui/issues/309).

**To Reproduce Steps to reproduce the behavior:**

**OPTIONAL: Expected behavior**
I would like to be able to select `label` as I would be able to select `Texte de la note` in the screenshot below.

**Screenshots**

![Capture d’écran 2019-11-07 à 14 33 44](https://user-images.githubusercontent.com/17294309/68393533-894f6900-016c-11ea-90f5-6497bfd81598.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G103), French
 - Browser Firefox 
 - Version 70.01.1

**Additional context**

**Comment by benjamingeer** [comment]
Since a label is not a Knora text value, we won't be able to support all the functionality that we offer for searching in text values. Do you just need to search for the exact contents of the label? Or do you also need wildcard searches in labels?

**Comment by mrivoal** [comment]
We would also need the wildcard searches. It will be useful per se but I also think it will be more consistent this way : users won't be puzzled by the fact they can use wildcard searches in some textfields and not in others.

**Comment by benjamingeer** [comment]
This is now implemented in `knora-api`. Support still needs to be added in `knora-ui` and `knora-app`.

**Comment by flavens** [comment]
@benjamingeer thank you

this issue has been moved to YouTrack: [DSP-346](https://dasch.myjetbrains.com/youtrack/issue/DSP-346)

new comments must be written in the YouTrack issue
