### ISSUE TITLE
Full text search results: grid view not well suited to resources other than knora-base:Representation

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#181]
**Describe the bug**
I assumed the purpose of grid view was to give a preview for subclasses of `knora-base:Representation`. 

I guess the preview doesn't work yet. 

**To Reproduce Steps to reproduce the behavior:**

**OPTIONAL: Expected behavior**
1) I don't think this view should be offered for resources other than subclasses of `knora-base:Representation`. For these resources, this view only show truncated texts.
2) or maybe the text context of these resources should simply not be displayed, but only the content of subclasses of `knora-base:Representation`

**Screenshots**
![Capture d’écran 2019-11-07 à 15 02 29](https://user-images.githubusercontent.com/17294309/68395329-c9fcb180-016f-11ea-8eb0-fddb51024aab.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G103), French
 - Browser Firefox 
 - Version 70.01.1

**Additional context**

**Comment by flavens** [comment]
this issue has been moved on YouTrack: [DSP-350](https://dasch.myjetbrains.com/youtrack/issue/DSP-350)
