### ISSUE TITLE
When `salsah-gui:guiOrder` is not define for a property, the property is not displayed

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#182]
**Describe the bug**
When `salsah-gui:guiOrder`, which should ideally be defined for each property is not define, then the property is not displayed at all, which is very strange because you can see the actual property displayed as a search criteria in the advanced search. And if you select this property, you will even see it displayed in the search results. But it disappears once you open a resource.

**To Reproduce Steps to reproduce the behavior:**
1. See the screenshot 1 for the advanced search criteria to reduce the bug.
2. Check the results in screenshot 2.
3. See the actual resource displayed without the property in screenshot 3.

**OPTIONAL: Expected behavior**
In Salsah 1.5, the properties are displayed anyway without paying attention to their order. I think this is the correct behaviour: not every project will use knora-app, or knora-ui to build a GUI. I don't think they will bother to define each `salsah-gui:guiOrder` in their ontologies, so I think these properties should be displayd anyway.

**Screenshots**

1.
![Capture d’écran 2019-11-08 à 11 35 14](https://user-images.githubusercontent.com/17294309/68470237-f0782680-021b-11ea-8f95-3776dd9ea3e3.png)

2.
![Capture d’écran 2019-11-08 à 11 35 24](https://user-images.githubusercontent.com/17294309/68470242-f2da8080-021b-11ea-82ff-83b5ea6c3b4e.png)

3.
![Capture d’écran 2019-11-08 à 11 35 39](https://user-images.githubusercontent.com/17294309/68470251-fa018e80-021b-11ea-8c02-b6491247f269.png)

The same resource in Salsah 1.5

![Capture d’écran 2019-11-08 à 11 37 18](https://user-images.githubusercontent.com/17294309/68470358-2fa67780-021c-11ea-882f-aa91f0d918f8.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G103), French
 - Browser Firefox 
 - Version 70.01.1

**Additional context**

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-349](https://dasch.myjetbrains.com/youtrack/issue/DSP-349)
