### ISSUE TITLE
Label of a resource should be displayed when the resource is opened

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#183]
**Describe the bug**
The label of a resource is displayed in the search results. But once you open one of the resources, the label is not displayed anywhere.

**To Reproduce Steps to reproduce the behavior:**

**OPTIONAL: Expected behavior**
Label should be displayed once a resource is opened.

**Screenshots**

![Capture d’écran 2019-11-07 à 16 18 54](https://user-images.githubusercontent.com/17294309/68401731-88253880-017a-11ea-911b-3b9266d2ebb0.png)

You couldn't tell the resource I am viewing is Sierra:
![Capture d’écran 2019-11-07 à 16 19 06](https://user-images.githubusercontent.com/17294309/68401742-8ce9ec80-017a-11ea-9079-2fff049cf73e.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G103), French
 - Browser Firefox 
 - Version 70.01.1

**Additional context**

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-348](https://dasch.myjetbrains.com/youtrack/issue/DSP-348)
