### ISSUE TITLE
Full text search with "_" doesn't give expected results

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#184]
**Describe the bug**
Full-text search with "_" doesn't give expected results. See also [knora-api issue #1434](https://github.com/dasch-swiss/knora-api/issues/1434).

**To Reproduce Steps to reproduce the behavior:**
Given this resource: 
![Capture d’écran 2019-09-10 à 14 35 17](https://user-images.githubusercontent.com/17294309/64614433-cd2a2a00-d3d8-11e9-9fe9-ad82529f2851.png)

The following search in unsuccessful:

![Capture d’écran 2019-09-10 à 14 40 13](https://user-images.githubusercontent.com/17294309/64614501-efbc4300-d3d8-11e9-82cf-8162dadb5e9b.png)

This one is even worse:

![Capture d’écran 2019-09-10 à 14 41 08](https://user-images.githubusercontent.com/17294309/64614589-19756a00-d3d9-11e9-83b8-6e4ee172264c.png)

**OPTIONAL: Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem (drag-and-drop the image directly here).

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G103), French
 - Browser Firefox 
 - Version 70.01.1

**Additional context**

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-357](https://dasch.myjetbrains.com/youtrack/issue/DSP-357)
