### ISSUE TITLE
Performance : full-text search for "est" takes a long time to load

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#185]
**Describe the bug**
Full-text search for "est" takes a long time to load if you click on "load more".

**To Reproduce Steps to reproduce the behavior:**
Search for “est” in All Projects in the full text search bar.
The search results are loaded in less than 5 seconds (4 sec).
However, if you click on `load more`, the loading of the results will take a long time . 54 secondes for me.

**OPTIONAL: Expected behavior**

**Screenshots**
![Capture d’écran 2019-11-07 à 17 25 30](https://user-images.githubusercontent.com/17294309/68407318-a2174900-0183-11ea-8d3c-b444a0c82809.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G103), French
 - Browser Firefox 
 - Version 70.01.1

**Additional context**

**Comment by flavens** [comment]
this issue has been resolved with the implementation of the pagination system.

this kind of search will be performed as a test in the new versions of DSP-APP to control loading time
