### ISSUE TITLE
The project selection list displays truncated projects's names

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#186]
**Describe the bug**
The project selection list displays truncated projects's name if there are too long (even though they are not *very* long).

**To Reproduce Steps to reproduce the behavior:**

**OPTIONAL: Expected behavior**
I see now that in the project creation form, you prevent the user from using a project name that is too long. But I find the max number of caracters allowed a bit too small, because a project's name has too remain significant as it is the entry point into the search functionalities. As the list of projects grows, I think 3 letters project name like MLS are not going to be significant enough for users external to the project. Thence the need for a bit more space in project name's definition.

However, I have been allowed to assign the name "abcdefghijklmnop" to a project. But when selected in the projects list, I can only see "abcdefghijklmn", which I find inconsistent.

**Screenshots**
![Capture d’écran 2019-11-08 à 10 52 10](https://user-images.githubusercontent.com/17294309/68467054-d76c7700-0215-11ea-8261-a304cba31845.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G103), French
 - Browser Firefox 
 - Version 70.01.1

**Additional context**
related issue by Gaby #206

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-353](https://dasch.myjetbrains.com/youtrack/issue/DSP-353)
