### ISSUE TITLE
Advanced search: a "select project" search criteria will be missing

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#187]
**Describe the bug**
Using the full-text search, user is invited to "filter by project".
When he switches to advanced search, he is invited to "select an ontology", which is not the same. 

In the future, we plan to use shared ontologies between various projects (e.g. a shared bibliography ontology would be very useful). But then, a search criteria in the advanced search will be missing, because choosing an ontology (e.g. bibliography) won't be enough: users will also want to limit the search to a specific project.

**To Reproduce Steps to reproduce the behavior:**

**OPTIONAL: Expected behavior**
I can see at least 2 options:
- add a search criteria to limit search within a specific project in the advanced search (which is the way Salsah 1.5 currently works), and if there is only one project using the chosen ontology  select this project by default in the search field
- or add the project as a faceted search criteria once the search query has been processed.

**Screenshots**
See Salsah screenshot:

![Capture d’écran 2019-11-08 à 11 12 21](https://user-images.githubusercontent.com/17294309/68468665-c5400800-0218-11ea-9e9d-30f76d0ba272.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G103), French
 - Browser Firefox 
 - Version 70.01.1

**Additional context**

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-292](https://dasch.myjetbrains.com/youtrack/issue/DSP-292)
