### ISSUE TITLE
Advanced search : combining 2 criteria doesn't always work (list + date, list + text)

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#189]
**Describe the bug**
In advanced search, I tried to combine 2 search criteria (comparison operator on a list and on a date on the one hand, comparison operator on a list and on a text on the other hand). See screenshot 1, 2 for the queries and screenshot 2 for the error.

If you make the same query in 2 distinct steps, you will see that this query should give results. In Salsah 1.5, these queries are performed without error.

**To Reproduce Steps to reproduce the behavior:**

**OPTIONAL: Expected behavior**

**Screenshots**
1. 
![Capture d’écran 2019-11-08 à 14 11 54](https://user-images.githubusercontent.com/17294309/68479092-c893bd80-0231-11ea-9099-d9f35e061749.png)

2. 
![Capture d’écran 2019-11-08 à 14 16 15](https://user-images.githubusercontent.com/17294309/68479334-5b345c80-0232-11ea-9bb6-306675958f22.png)

3. 
![Capture d’écran 2019-11-08 à 14 12 06](https://user-images.githubusercontent.com/17294309/68479121-dc3f2400-0231-11ea-989f-335a111da267.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G103), French
 - Browser Firefox 
 - Version 70.01.1

**Additional context**

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-356](https://dasch.myjetbrains.com/youtrack/issue/DSP-356)
