### ISSUE TITLE
Advanced search : when the search criteria is a boolean, the sort criterion box is confusing

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#190]
**Describe the bug**
Advanced search : when the search criteria is a boolean, the sort criterion is confusing : I didn't know which box should be ticked to perform the search on "true".

**To Reproduce Steps to reproduce the behavior:**

**OPTIONAL: Expected behavior**

**Screenshots**

![Capture d’écran 2019-11-08 à 14 22 48](https://user-images.githubusercontent.com/17294309/68479707-44423a00-0233-11ea-8c40-eae88813f255.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G103), French
 - Browser Firefox 
 - Version 70.01.1

**Additional context**

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-354](https://dasch.myjetbrains.com/youtrack/issue/DSP-354)
