### ISSUE TITLE
Search results display : the number of results displayed should be specified

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#191]
**Describe the bug**
Only the total number of search results is specified. But I think the user should also know how many results on the total he is currently viewing (e.g. 50 of 193).

**To Reproduce Steps to reproduce the behavior:**

**OPTIONAL: Expected behavior**

**Screenshots**

![Capture d’écran 2019-11-08 à 14 46 36](https://user-images.githubusercontent.com/17294309/68481098-99cc1600-0236-11ea-9172-50f40941f6e8.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G103), French
 - Browser Firefox 
 - Version 70.01.1

**Additional context**

**Comment by flavens** [comment]
This issue has been resolved by implementing the paginator component from Angular Material.
I could not find the related PR, but here is a screen shot of a search result list:
 
<img width="1190" alt="Screenshot 2020-02-04 at 09 30 59" src="https://user-images.githubusercontent.com/29532462/73727290-73cce980-4731-11ea-9c46-3bfbc5860ff3.png">
