### ISSUE TITLE
Search list results : why not allowing a right-click on a result to open it in a new window 

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#192]
**Describe the bug**
Spontaneously, I would like to be able to right-click on a search result to open it in a new window or tab.

**To Reproduce Steps to reproduce the behavior:**

**OPTIONAL: Expected behavior**

**Screenshots**
If applicable, add screenshots to help explain your problem (drag-and-drop the image directly here).

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G103), French
 - Browser Firefox 
 - Version 70.01.1

**Additional context**

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-358](https://dasch.myjetbrains.com/youtrack/issue/DSP-358)
