### ISSUE TITLE
Resource viewer : a right-click on a link to open the link in a new window/tab

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#193]
**Describe the bug**
Spontaneously, I would like to be able to right-click on the links displayed for a resource to open them in a new window or tab.

**To Reproduce Steps to reproduce the behavior:**

**OPTIONAL: Expected behavior**

**Screenshots**
![Capture d’écran 2019-11-08 à 15 09 59](https://user-images.githubusercontent.com/17294309/68482436-e49b5d00-0239-11ea-897e-5361b0dfd0a8.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G103), French
 - Browser Firefox 
 - Version 70.01.1

**Additional context**

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-351](https://dasch.myjetbrains.com/youtrack/issue/DSP-351)
