### ISSUE TITLE
Unspecified error when opening a resource

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#194]
**Describe the bug**
I had the following error (screenshot 1) when I tried to open the Thing "testding".

**To Reproduce Steps to reproduce the behavior:**
1. In the full-text search bar, search for "testding"
2. Try to open the search result.

**OPTIONAL: Expected behavior**

**Screenshots**
![Capture d’écran 2019-11-08 à 15 18 40](https://user-images.githubusercontent.com/17294309/68483040-1234d600-023b-11ea-83c0-a19e6fa8d2f0.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G103), French
 - Browser Firefox 
 - Version 70.01.1

**Additional context**

**Comment by flavens** [comment]
there must be an error in the data at the time of the test phase because it cannot be reproduced now with the new version of DSP-API (v13.0.0-rc.4 during the test locally)
