### ISSUE TITLE
Expert search : when the query is long, there is an overlap with elements from the form

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#195]
**Describe the bug**
See screenshot.

**To Reproduce Steps to reproduce the behavior:**

**OPTIONAL: Expected behavior**

**Screenshots**

![Capture d’écran 2019-11-08 à 15 36 10](https://user-images.githubusercontent.com/17294309/68484446-8e301d80-023d-11ea-8804-b7d65853bd09.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G103), French
 - Browser Firefox 
 - Version 70.01.1

**Additional context**

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-359](https://dasch.myjetbrains.com/youtrack/issue/DSP-359)
