### ISSUE TITLE
The ARK ID of a resource should be displayed (or at least its IRI)

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#196]
**Describe the bug**
I think the display of the identifier of a resource is crucial. Even if no ARK server is currently configured, the IRI of each resource could already be visible.

It will help figuring out that the resources we get as search results are not duplicates, but different resources (see #156). And I guess it would help you take the necessary space for this feature into account in the next developments.

IRIs/ARK ID should be visible in the search results and of course on the page of each resource, along with the label of the resource (#183).

**To Reproduce Steps to reproduce the behavior:**

**OPTIONAL: Expected behavior**
IRIs/ARK ID should be visible in the search results and of course on the page of each resource, along with the label of the resource (#183).

**Screenshots**
If applicable, add screenshots to help explain your problem (drag-and-drop the image directly here).

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G103), French
 - Browser Firefox 
 - Version 70.01.1

**Additional context**

**Comment by flavens** [comment]
the implementation of the ARK ID is already planned

**Comment by flavens** [comment]
this issue has been moved to GitHub: [DSP-5](https://dasch.myjetbrains.com/youtrack/issue/DSP-5)
