### ISSUE TITLE
Error on the home page after loggin out as a system admin

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#198]
**Describe the bug**
I got an error on the home page after loggin out as a system admin

**To Reproduce Steps to reproduce the behavior:**
I don't exactly. I was using Chrome, this time. I logged out for the user dashboard and then clicked on the lamp on the left corner. I scrolled down and saw the error.

**OPTIONAL: Expected behavior**

**Screenshots**
![Capture d’écran 2019-11-08 à 17 23 50](https://user-images.githubusercontent.com/17294309/68493490-d73b9e00-024c-11ea-86ec-6d869c9ccf41.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.14.6 (18G103), French
* Browser Chrome 
* Version 78.0.3904.97

**Additional context**

**Comment by flavens** [comment]
I could not be able to reproduce the error....
