### ISSUE TITLE
Changing User Password window is not clear.

### ISSUE THREAD

**Issue by GabyKuster** [dasch-swiss/knora-app#201]
1. I am logged in as a Sys admin
2. I changed the password of a project user
3. I get a confirmation window (see image)
4. I think the confirmation window should be without functionality: 

- the window has an **active** button "zurücksetzen" which does not make any sense in this context
- In the window there are still the fields Password/ Confirm password active, this is missunderstandingly. There first time I changed the password and got this window, I thought I made something wrong and have to fill in the form fields again.

**Screenshots**
![image](https://user-images.githubusercontent.com/56250095/68566792-a085a380-0457-11ea-9e13-65f007d30f4b.png)

**Desktop (please complete the following information):**
* OS: Windows 10 Pro N, 1903 - 18362.418
* Browser Google Chrome, 78.0.3904.97

* Version Knora App, 1.6.2

**Additional context**

**Comment by GabyKuster** [comment]
The button "zurücksetzen" is also constantly active in other windows, e.g. Benutzer Anpassen" where a user can change name and language. THis button should only get active, when something was changed

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-360](https://dasch.myjetbrains.com/youtrack/issue/DSP-360)
