### ISSUE TITLE
User can reactivate his deactivated account!

### ISSUE THREAD

**Issue by GabyKuster** [dasch-swiss/knora-app#203]
1. I am logged in as a member user,
2. The sys admin deactivates my account
3. The system does not suspend me, I can stay logged in (see #199)
4. I can actually use all functions available and e.g. change my password
5. In the change password window I can even "reactivate" my account!!
6. see image

**Screenshots**
![image](https://user-images.githubusercontent.com/56250095/68567963-9022f800-045a-11ea-9201-20bbba7beb39.png)

**Desktop (please complete the following information):**
* OS: Windows 10 Pro N, 1903 - 18362.418
* Browser Google Chrome, 78.0.3904.97

* Version Knora App, 1.6.2

**Additional context**

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-344](https://dasch.myjetbrains.com/youtrack/issue/DSP-344)
