### ISSUE TITLE
Wording: Mix of language

### ISSUE THREAD

**Issue by GabyKuster** [dasch-swiss/knora-app#204]
I found in several places, that the language of the menu and descriptions is not consistent, e.g. "Projekt löschen", combined with "do you want to delete this project?"

**Screenshots**
![image](https://user-images.githubusercontent.com/56250095/68568642-72ef2900-045c-11ea-81f7-393fcd2c7766.png)

**Desktop (please complete the following information):**
* OS: Windows 10 Pro N, 1903 - 18362.418
* Browser Google Chrome, 78.0.3904.97

* Version Knora App, 1.6.2

**Additional context**

**Comment by kilchenmann** [comment]
This is because of the translation service, which is not fully implemented. Some sentences are already translated, but if a phrase doesn't exist in german, the app takes the english one.

**Comment by kilchenmann** [comment]
About the multilanguage / i18n integration, the following article could also be interesting:
[Multi-Language Date Formats with Angular Material](https://medium.com/@kristinahertmann/multi-language-date-formats-with-angular-material-b8598415d117)

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-361](https://dasch.myjetbrains.com/youtrack/issue/DSP-361)
