### ISSUE TITLE
Archived Project: menu in red?

### ISSUE THREAD

**Issue by GabyKuster** [dasch-swiss/knora-app#205]
1. As a project admin I open an project, that has been "archived".
2. The menu options are displayed in red, and I get the impression, that I do something forbidden.
3. As I understand from discussions with Flavie, "archived" means: No more changes are done to project data, so actually the project is in a kind of "read only" status. For that reason I would use a different color code for archived projects and only red warnings, when somebody tries do reactivate it in order to show, what consequences there would be.

![image](https://user-images.githubusercontent.com/56250095/68568985-4b4c9080-045d-11ea-81eb-f3257c8439cd.png)

**Desktop (please complete the following information):**
* OS: Windows 10 Pro N, 1903 - 18362.418
* Browser Google Chrome, 78.0.3904.97

* Version Knora App, 1.6.2

**Additional context**

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-362](https://dasch.myjetbrains.com/youtrack/issue/DSP-362)
