### ISSUE TITLE
Long project names are truncted in search window

### ISSUE THREAD

**Issue by GabyKuster** [dasch-swiss/knora-app#206]
A Long project name, e.g. Lumieres-Lausanne is too long for the dedicated area in the search window. Part of the project name is cut off.

**Screenshots**
![image](https://user-images.githubusercontent.com/56250095/68569314-1c82ea00-045e-11ea-9fca-37a62190a6ce.png)

**Desktop (please complete the following information):**
* OS: Windows 10 Pro N, 1903 - 18362.418
* Browser Google Chrome, 78.0.3904.97

* Version Knora App, 1.6.2

**Additional context**
related issue by Marion #186

**Comment by flavens** [comment]
this issue has been resolved
