### ISSUE TITLE
Wording: change label "System" to "Manage projects"

### ISSUE THREAD

**Issue by flavens** [dasch-swiss/knora-app#213]
**Describe the bug**

Marion:  I think that the wording "System" could be improved. 

Something like "Manage projects" (or anything alike) would be clearer, IMO.

**Comment by flavens** [comment]
@mrivoal we need to discuss the term because 'System' is more than just 'Manage projects'. It is the management panel for all projects, all users, and maybe more in the future (like statistics) only accessible for System admin users.

**Comment by mrivoal** [comment]
I see. But IMHO, as a `ProjectAdmin`, if I were to manage a project (e.g. add create users, etc.), I am not sure I would look into the `System` tab. Indeed, I didn't during user testing.

Why not looking at something broader and more classical like "Administration" or "Management"?

**Comment by flavens** [comment]
We are not really satisfied by all the label names we could think of... The main dashboard will be improved in admin-dashboard-panel style and then the System button in the menu will no longer be useful. I keep this term at the moment until the refactoring.

**Comment by flavens** [comment]
@kilchenmann if it is ok for you that we'll rather use the term "admin" e.g. project admin, system admin, as suggested by Regula?

**Comment by kilchenmann** [comment]
Yes for me it's fine. It's what we had in a previous version 😂

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-379](https://dasch.myjetbrains.com/youtrack/issue/DSP-379)
