### ISSUE TITLE
Metadata (who created, when) should be displayed for values and resources

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#216]
**Describe the bug**
In Salsah 1.5, if you mouse over the icon "i" for a value, you get metadata as to who created this value and when. It is a very useful feature that should be implemented in Knora-app.
I always though that it should be implemented at resource level as well. 

**To Reproduce Steps to reproduce the behavior:**

**OPTIONAL: Expected behavior**

**Screenshots**
![Capture d’écran 2019-11-12 à 15 26 08](https://user-images.githubusercontent.com/17294309/68679790-d4002500-0560-11ea-878a-bed2501d0df3.png)

**Desktop (please complete the following information):**
* OS: [e.g. iOS]
* Browser [e.g. chrome, safari]
* Version [e.g. 22]

**Additional context**

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-369](https://dasch.myjetbrains.com/youtrack/issue/DSP-369)
