### ISSUE TITLE
Wrong redirection after removing myself as project admin in project collaboration

### ISSUE THREAD

**Issue by flavens** [dasch-swiss/knora-app#220]
**Describe the bug**
When I (user flaurens - system admin) want to remove myself as project admin in one project (e.g. Anything), I am redirected to the project description page, no toolbar menu displayed (http://0.0.0.0:4200/project/0001/info). Probably user permission as project admin involved.

**To Reproduce**
1. Go to 'http://0.0.0.0:4200/project/0001/collaboration'
2. Add yourself as project admin
3. Click on Remove as project admin
4. See error --> redirection to http://0.0.0.0:4200/project/0001/info

**Expected behavior**
It should reload the content of the collaboration page - no redirection. 

**Versions:**
 - OS: MacOS CAtalina
 - Browser: Chrome
 - master branch
 - Knora tag v11.0.0

**Additional context**
It works well with other users than my own account on other projects.

**Comment by kilchenmann** [comment]
I'm not able to reproduce the issue. But I still have knora-api v10.1.1
I'll update the version and test it again

**Comment by kilchenmann** [comment]
...no, I'm not able to reproduce your issue. 

> It should reload the content of the collaboration page - no redirection.

There's no redirection defined. The refresh is defined as follow:
```typescript
refresh(): void {
  // referesh the component
  this.loading = true;
  this.initList();
}
```

**Comment by kilchenmann** [comment]
But I see, there's an issue in "session" in the localStorage. The logged-in user should have an array of project IRIs, where she/he's project admin. But in my case the list is empty.

**Comment by kilchenmann** [comment]
I will fix all issues here. You're right...in another part in users-list is a redirection to project page. I don't remember why

**Comment by kilchenmann** [comment]
> project description page, no toolbar menu displayed 

a „normal“ user without system or project admin rights does not have access to collaboration, groups, data model an lists in the admin interface of project. @flavens we can discuss it today whether this is the right approach.
