### ISSUE TITLE
Description cannot be deleted in lists and bug with empty language values

### ISSUE THREAD

**Issue by kilchenmann** [dasch-swiss/knora-app#224]
**Describe the bug**
- It's not possible to delete an existing (stringLiteral) comment in list info. An empty value will not override the existing one. 
- In case of not-defined language in label or comment, we get an ugly form and it's not possible to add a language to the value later on.

**To Reproduce**
- Open a project and go to lists where you have the rights to edit list info. Go to "edit" list. Try to remove existing description by deleting all values in the textarea.
- Open a list-info where the language for label is not defined. This is hard to reproduce as long you don't have this kind of data.

**Expected behavior**
- In case of existing description, make the field required. If a user deletes the existing description, the submit button should be disabled.
- In case of missing language, give the possibility, to select language and assign to existing value.

**Additional context**

This could be one solution for the issue about "delete" description.

```html
<button mat-raised-button type="submit" color="primary" [disabled]="labels.length === 0 || (iri && comments.length === 0)" (click)="submitData()">
    {{ iri ? 'Update' : 'Next' }}
</button>
```

Or set field in edit mode and with existing value  to "required". This can be done in the formGroup definition

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-372](https://dasch.myjetbrains.com/youtrack/issue/DSP-372)
