### ISSUE TITLE
Project-specific groups supported in Knora app (admin interface) : timeline ?

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#230]
Hello @kilchenmann and @flavens,

Just a question: I would like our users to be able to create lists using Knora-app (Knora Web App v1.6.3). But some of our projects use a project-specific administrator group, which mean that the built-in `ProjectAdmin` group is not used at all. 

Since the project-specific groups are not supported yet, this also means that no matter what the administrative permission for the project-specific admin group, a user from this group won't be able to see the tabs related to administrative tasks (Collaboration, Permission groups, Data model, Lists) in his dashboard. He can't create a list.

For now, I will just create factice users which are in Knora `ProjectAdmin` built-in group and add administrative permission so that this group can perform administrative tasks. But I was wondering if you already know approximately when the project-specific groups will be supported in Knora-app's admin interface and how long I will have to use this workaround ?

**Comment by flavens** [comment]
@mrivoal we are aware of this situation. However this new feature is not planned for (at least) the first trimester, we have other priorities on our hands. If this trick works for you at the moment, go on.

**Comment by mrivoal** [comment]
Ok, thanks for the reply. We can live with that for now. 

Do you know if it also means that these projects won't be able to use Knora app to edit resources at all until project specific groups are implemented, right?

**Comment by flavens** [comment]
No I am working with Tobias to implement the new resource viewer with the CRUD operations included. Hope to release it within 2-3 months.

**Comment by mrivoal** [comment]
Great! Thanks.

**Comment by subotic** [comment]
> Since the project-specific groups are not supported yet, this also means that no matter what the administrative permission for the project-specific admin group, a user from this group won't be able to see the tabs related to administrative tasks (Collaboration, Permission groups, Data model, Lists) in his dashboard. He can't create a list.

@flavens Why is it like this? The groups a user is in has no barring on the permissions a user has, i.e., a user in the `ProjectAdmin` group won't have ProjectAdmin permissions if the group itself is not defined in such way. We should sit down next week and have a quick look.

**Comment by flavens** [comment]
@subotic I do not fully understand what you mean. We can discuss it next week.
