### ISSUE TITLE
Is it already possible to create a multilingual list?

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#231]
Just wondering if I can't find the right way to do it or if this feature is not supported yet (Knora Web App v1.6.3)

**Comment by flavens** [comment]
@mrivoal yes it is possible to create multilingual list. The edition of the label and description is implemented but not the edition of the list itself.

**Comment by mrivoal** [comment]
Hum... Well I tried but I couldn't figure how to create a list entry with both an english and a french translation. Could you maybe show me how with a quick video (or point to a documentation)?

**Comment by flavens** [comment]
You can check this doc: https://docs.dasch.swiss/user-guide/project/#lists
If it is not enough, I can create a short video demo.

**Comment by mrivoal** [comment]
Thanks! It works. I think I was confused by the fact that once you have entered the first translation, there is really no sign showing that the system has recorded it... So I thought it didn't work.
