### ISSUE TITLE
A SystemAdmin/ProjectAdmin user is unable to deactivate a ProjectMember

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#233]
**Describe the bug**
It looks as if a `SystemAdmin` or a `ProjectAdmin` (with a `ProjectAdminAllPermission` permission ) were unable to deactivate a `ProjectMember`. Or at least neither I (Knora Web App v1.6.3) nor @gfoo (Knora Web App v2.0.0) found how to do it.

It looks like only a user can deactivate itself. And reactivate himself (#203).

**To Reproduce**

**Expected behavior**
A `SystemAdmin` and a `ProjectAdmin` (with a `ProjectAdminAllPermission` permission) should be able to deactivate a `ProjectMember`.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6 (18G1012)
 - Browser : Safari and Firefox

**Additional context**

**Comment by kilchenmann** [comment]
> A SystemAdmin and a ProjectAdmin (with a ProjectAdminAllPermission permission) should be able to deactivate a ProjectMember.

As SystemAdmin or as ProjectAdmin you can add users to the project and you can remove from the project. --> https://docs.dasch.swiss/user-guide/project/#collaboration


Only SystemAdmin can deactivate (suspend) a user completely. This function is in the list of all users in the `/system`-view. --> https://docs.dasch.swiss/user-guide/system/#all-users

**Comment by mrivoal** [comment]
>As SystemAdmin or as ProjectAdmin you can add users to the project and you can remove from the project. --> https://docs.dasch.swiss/user-guide/project/#collaboration

This I saw easily. Great.

> Only SystemAdmin can deactivate (suspend) a user completely. This function is in the list of all users in the /system-view. --> https://docs.dasch.swiss/user-guide/system/#all-users

And this I forgot. As I said in #234, I will now look to the documentation before posting any new issue, sorry.

**Comment by kilchenmann** [comment]
> And this I forgot.

Easy, no problem. We know the link to the list of all users is a bit hidden.
