### ISSUE TITLE
A SystemAdmin should be able to view all the users, including users removed from projects

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#234]
**Is your feature request related to a problem? Please describe.**
Once a User is removed from a project, a `SystemAdmin` should be able to see it, for example to deactivate it. But it looks as if the only way to see the current Users in Knora was by choosing first a project and see the Users related to it.

![Capture d’écran 2020-01-09 à 17 12 26](https://user-images.githubusercontent.com/17294309/72084354-9e2eb100-3303-11ea-88b1-3d6fee536873.png)

**Describe the solution you'd like**
A `SystemAdmin` should be able to see all Users. Maybe under the lits of projects, on the dashboard? 

**Describe alternatives you've considered**

**Additional context**

**Comment by flavens** [comment]
Are you talking about a list like this one? https://docs.dasch.swiss/user-guide/system/#all-users

**Comment by mrivoal** [comment]
Yes. Sorry, I see now that it is in the "system" menu. 

It may be because of the wording... I see now that I am, at least, consistent :) (#213)

I will now look to the documentation before posting any new issue.
