### ISSUE TITLE
Currently, only a SystemAdmin can change a user's password

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#239]
**Is your feature request related to a problem? Please describe.**
According to the documentation, only a `SystemUser` can edit a user's password. 

**Describe the solution you'd like**
I think a `ProjectAdmin` should be able to do as well, as long as there is no way for a user to change his own password, otherwise SystemAdmin will spend a lot of time doing it.

**Describe alternatives you've considered**

**Additional context**

**Comment by kilchenmann** [comment]
This is a restriction from knora. We have to discuss, how we and who can manage user data.

**Comment by flavens** [comment]
N.B.: a user can change his own password if he remembers his old one.

**Comment by mrivoal** [comment]
Yes, but this is not the most common use case for the changing a password :)

**Comment by gfoo** [comment]
Don't forget that the main problem at the beginning of this issue (mainly related to our LL project) is that a user cannot re-initialize its own password by receiving an email (quite common today as u know)

**Comment by kilchenmann** [comment]
As you know, we will implement as soon as it's ready (and we have the time), the [Switch edu-id](https://www.switch.ch/edu-id/) which handles the user access incl. user management. It doesn't make sense to create a password recovery service when it will be replaced by an already existing service.

**Comment by mrivoal** [comment]
@kilchenmann, it makes sense, of course.

However, I still think a `ProjectAdmin` should be able to change the user's passwords of the project is entitled to manage. @subotic, what are your thoughts on the matter?

**Comment by subotic** [comment]
@mrivoal While I understand your point, I don't like the idea that a project admin can change user passwords.

We should rather have a "reset password" option which will send a new password to the user by Email. Let me think about it and see if we can implement this more quickly. Knora needs to be able to send Emails anyway. The project admin can then click on the "reset password" button for a certain user.

**Comment by mrivoal** [comment]
> The project admin can then click on the "reset password" button for a certain user.

That would be the best solution, of course.

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-373](https://dasch.myjetbrains.com/youtrack/issue/DSP-373)
