### ISSUE TITLE
A system admin cannot set another user as system admin

### ISSUE THREAD

**Issue by flavens** [dasch-swiss/knora-app#244]
**Describe the bug**
On System > All Users, a system admin wants to give the role of System Admin to another user, but nothing happens. A 400 Bad request error is thrown.

**To Reproduce**
1. Go to 'http://0.0.0.0:4200/system/users'
2. Click on 'Add as system admin' in one user menu
4. See error in the console log

**Expected behavior**
A non-system-admin user can get the role system admin.

**Screenshots**
<img width="1010" alt="Screenshot 2020-01-22 at 15 02 50" src="https://user-images.githubusercontent.com/29532462/72900827-e2b94400-3d28-11ea-8101-29991867da11.png">

<img width="1167" alt="Screenshot 2020-01-22 at 15 02 37" src="https://user-images.githubusercontent.com/29532462/72900841-e8168e80-3d28-11ea-97ac-353de6a468cd.png">

<img width="881" alt="Screenshot 2020-01-22 at 15 03 12" src="https://user-images.githubusercontent.com/29532462/72900848-ea78e880-3d28-11ea-8735-38bd6d6802a4.png">

<img width="867" alt="Screenshot 2020-01-22 at 15 03 19" src="https://user-images.githubusercontent.com/29532462/72900858-ed73d900-3d28-11ea-9818-f1ff0eff9304.png">

**Desktop (please complete the following information):**
 - OS: MacOS Catalina 10.15.2
 - Browser: Google Chrome
 - Version: Version 79.0.3945.117 (Official Build) (64-bit)

**Comment by kilchenmann** [comment]
The knora-api-js-lib users-endpoint method to `updateUserSystemAdminMembership` needs user data of type `storedUser`, which we don't have. There's an open question about this type: dasch-swiss/knora-api#1579

**Comment by flavens** [comment]
the lib should be ready to fix this issue, the PR has been merged: https://github.com/dasch-swiss/knora-api-js-lib/pull/138

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-374](https://dasch.myjetbrains.com/youtrack/issue/DSP-374)
