### ISSUE TITLE
[Knora-app resource viewer mockup] What is the point for the resource path ?

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#261]
**Is your feature request related to a problem? Please describe.**
I don't really see the point for this path under the tab menu? 

**Describe the solution you'd like**
If the point is to display the ARK ID (which is generally referred to as an identifier rather than an URL), I think I would prefer to see the ARK clearly displayed as: "Identifier : ark:/12148/bpt6k107371t". 

**Additional context**
![Capture d’écran 2020-02-24 à 14 36 09](https://user-images.githubusercontent.com/17294309/75156777-2251c200-5713-11ea-8608-bf46f8e6adb4.png)

**Comment by flavens** [comment]
@mrivoal thanks for the feedback, it is a good idea to present the ARK URL as an identifier. However, it would be good to keep the hierarchy project > ontology > resource with links somewhere. We will think about it!

**Comment by mrivoal** [comment]
I find the idea interesting,. This way the user knows where he's landing. 

However, Project shortname + ontologie label is likely to bring some redundancy, ex. : lumiere-lausanne > The Lumières.Lausanne ontology
or incunabula > The Incunabula ontology

The most common cases is one project = one ontology.

**Comment by flavens** [comment]
we can shorten it to the project that's fine, the user needs the info somewhere

**Comment by flavens** [comment]
this suggestion has been taken into consideration in the latest version of the mockup
