### ISSUE TITLE
[Knora-app resource viewer mockup] Unsure of the meaning of some icons in the property view? 

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#262]
**Is your feature request related to a problem? Please describe.**
I don't understand what this icon stands for?

**Additional context**
![Capture d’écran 2020-02-24 à 14 49 30](https://user-images.githubusercontent.com/17294309/75157910-5af29b00-5715-11ea-93f5-2847a2fa37d1.png)

**Comment by flavens** [comment]
@mrivoal there are some explanations about these icons in the notes of the mockup. This one is to visualise the resource in a graph view.

**Comment by mrivoal** [comment]
I didn't found explantations yet...

It is my opinion, of course, but I don't think this icon refers to a graph. But as these are mockup, maybe I shouldn't be so specific?

**Comment by flavens** [comment]
We picked the most relevant icon in the software library but we won't have access to the same specific icons with Material icon library. I think the most important idea is the meaning of the element (button/icon), not the graphic element that can be discussed and changed easily in comparaison with container/div/text position for instance.

**Comment by mrivoal** [comment]
Ok, thanks for the clarification. I will keep this in mind.

**Comment by mrivoal** [comment]
I will close the non-relevant issues.
