### ISSUE TITLE
[Knora-app resource viewer mockup] What exactly does the hyperlink icon stands for in the property view?  

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#263]
**Is your feature request related to a problem? Please describe.**
Does the hypertext icon stands for citing an ARK? If so, I don't really like it because an ARK ID is more that a simple hyperlink.

**Describe the solution you'd like**
Lots of data providers usually display their (persistent) IDs in full text and I think I like this better because it underline its importance of it. See https://www.loc.gov/item/2012645482/. 

If the hyperlink icon was to use to cite a full resource (which would be great), it should be a complex citation of data something like: 
> Barnes, Samuel H. Italian Mass Election Survey, 1968. Ann Arbor, MI: Inter-university Consortium for Political and Social Research [distributor], 1992-02-16. https://doi.org/10.3886/ICPSR07953.v1

**Additional context**
![Capture d’écran 2020-02-24 à 15 07 04](https://user-images.githubusercontent.com/17294309/75158939-6f379780-5717-11ea-8177-fbaa2723f4b8.png)

**Comment by flavens** [comment]
@mrivoal I have no idea, I will ask @kilchenmann

**Comment by kilchenmann** [comment]
This is the link button to link this resource to another resource directly. Known from old salsah (there it was at the top header) to connect two resources.

**Comment by kilchenmann** [comment]
"for citing an ARK" you have to use the share menu.
