### ISSUE TITLE
[Knora-app resource viewer mockup] Unsure of the meaning of some icons in the property view? (2)

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#264]
**Is your feature request related to a problem? Please describe.**
To me, this icon means "log out". But I wouldn't expect it here (but rather in the user zone, at the top right hand corner), so I guess it means something else?

**Additional context**
![Capture d’écran 2020-02-24 à 15 12 14](https://user-images.githubusercontent.com/17294309/75159277-174d6080-5718-11ea-8e00-138a6abcc44c.png)

**Comment by flavens** [comment]
@mrivoal this icon should mean "share" resource. André did this mockup, I haven't modify his work. These 4 icons represent possible operations on the resource such as sharing, viewing in a specific way, saving in favourite...

**Comment by mrivoal** [comment]
Non relevant issue at mock-up stage (see https://github.com/dasch-swiss/knora-app/issues/262#issuecomment-590751795).
