### ISSUE TITLE
[Knora-app resource viewer mockup] Incoming links and annotation in the same tab/panel

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#265]
**Is your feature request related to a problem? Please describe.**
I don't really like the idea of incoming links and annotations being in the same tab. They were separated somehow in Salsah and I think it was better because they are not exactly the same thing.

Incoming links are generally created within the scope of a project, while annotation can come from everywhere (if I understand correctly). For this reason, I would keep them in distinct space.

**Additional context**

![Capture d’écran 2020-02-24 à 15 41 04](https://user-images.githubusercontent.com/17294309/75161456-23d3b800-571c-11ea-908b-c7177a7e06bd.png)

**Comment by flavens** [comment]
@mrivoal as mention in my email, André placed this container here. I will talk to him because I am not convince about this container at this place. I would prefer having 2 expansion-panels after the prop list.

**Comment by flavens** [comment]
this suggestion has been taken into consideration in the latest version of the mockup (v4).
