### ISSUE TITLE
[Knora-app resource viewer mockup] Missing mandatory rdfs:label property 

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#267]
**Is your feature request related to a problem? Please describe.**
I don't see anywhere the mandatory knora-base property `rdfs:label` for every resource. In Salsah, this is this property that permits to define a link from one resource to another in a pulldown menu. I think you will need to add it somewhere... 

This property is also tricky because most of the time it implies redundancy with at least another property of a resource. Users need to define a schema for this property for every resource in the ontology and stick to it so that they could retrieve the correct data when they want to create a link between 2 resources. 

As the wording "label" is quite difficult to understand for users, I think it would good to find a better term in the process. 

**Additional context**

![Capture d’écran 2020-02-25 à 10 35 39](https://user-images.githubusercontent.com/17294309/75234333-b4f96c00-57ba-11ea-8f46-a857fafc0b7a.png)

**Comment by flavens** [comment]
@mrivoal in the example above, is the Label a combination of Titre de la légende + Numéro de vitrine?
Is the resource label/name?

**Comment by mrivoal** [comment]
In this case, yes, but it is done manually. And depending on the resource classe, the syntax of the label will change. In the case of a book, for example, you may want to include the title, the date and possibly the author's name in the label. It depends on the users' wills and needs.

And it is this property which is currently used in Salsah in a combobox to search and retrieve an existing resource on which you want to make a link. If I am not clear enough, let me know.

![Capture d’écran 2020-02-27 à 10 52 02](https://user-images.githubusercontent.com/17294309/75432767-37b33000-594f-11ea-8277-cab8512c3ec8.png)

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-378](https://dasch.myjetbrains.com/youtrack/issue/DSP-378)

**Comment by kilchenmann** [comment]
![Screen Shot 2021-07-19 at 08 59 06](https://user-images.githubusercontent.com/4253580/126116934-237bbcb0-325a-41b8-bf8c-63dc73cefd2c.png)
