### ISSUE TITLE
[Knora-app resource viewer mockup] properties-viewer-create-mode : hint message

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#269]
**Is your feature request related to a problem? Please describe.**
> Hint message informs the user what is expected in the field with an example if necessary.

I don't understand where would this hint message come from? From the ontology? From a global hint schema provided by knora-app depending of the type of a property (DateValue, TextValue, UriValue, etc?).

**Comment by flavens** [comment]
@mrivoal an hint message would come from a global hint schema provided by knora-app depending of the type of a property (DateValue, TextValue, UriValue, etc?) and be optional (some types like "boolean" with a checkbox as GUI element are too obvious)

**Comment by flavens** [comment]
Hint messages are now part of the value components in the viewer module
