### ISSUE TITLE
[Knora-app resource viewer mockup] properties-viewer-read-create-edit-mode : the annotation panel takes a lot of space

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#270]
**Is your feature request related to a problem? Please describe.**
I think I need another explanation on what an annotation is. 
What I can say for now is that these feature doesn't seen to be used a lot at the moment and this might be the reason for it is so blurry to me... Unless it is the other way around. So, anymore information about it would be good.

However, if little use is made of annotation, I don't think it should take so much space in the form. Ideally, it could be a side panel the user can choose to reduce/expand according to its own use.

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-376](https://dasch.myjetbrains.com/youtrack/issue/DSP-376)
