### ISSUE TITLE
[Knora-app resource viewer mockup] properties-viewer : how to delete a resource?

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#271]
**Is your feature request related to a problem? Please describe.**
It may be off topic because the mock-up focuses on property editing operation. But in case it isn't, here is the thing: I don't see how a user could delete a whole resource.

**Comment by flavens** [comment]
@mrivoal a button should be added somewhere, as well as one to create a whole new resource instance. We have to think about it. If you have some idea, let me know!

**Comment by flavens** [comment]
this issue has been mentioned on YouTrack: [DSP-143](https://dasch.myjetbrains.com/youtrack/issue/DSP-143)
