### ISSUE TITLE
[Knora-app resource viewer mockup] properties-viewer-read-create-edit-mode : how to set specific permission on the value of a property ?

### ISSUE THREAD

**Issue by mrivoal** [dasch-swiss/knora-app#272]
**Is your feature request related to a problem? Please describe.**
Users granted with this permission (`CR` = change rights) should also be able to set a given permission for the value of a property, thus overwriting the default permissions globally attached to a property.

Mock-ups don't show this feature, yet, do they? How do think you will integrate it?

**Comment by flavens** [comment]
@mrivoal no I haven't added it to the mockup. Need to check with Tobias and the value elements.

**Comment by flavens** [comment]
In Salsah, is the locker icon used to change value permissions?

![75234333-b4f96c00-57ba-11ea-8f46-a857fafc0b7a](https://user-images.githubusercontent.com/29532462/75433215-e5264380-594f-11ea-834b-a9c785f19090.png)

**Comment by mrivoal** [comment]
It is supposed to but it doesn't work. 

![Capture d’écran 2020-02-27 à 10 58 44](https://user-images.githubusercontent.com/17294309/75433446-3e8e7280-5950-11ea-9a3f-838e499a25fa.png)

**Comment by flavens** [comment]
this required modification has been taken into consideration in the last version of the mockups (see GDrive > mockup-v4)
