### ISSUE TITLE
Responsive style issue in project admin view

### ISSUE THREAD

**Issue by kilchenmann** [dasch-swiss/knora-app#273]
**Describe the bug**
The content header in the project admin container (e.g. team, list or ontology view) is not responsive enough and the tab bar (main project header) disappears on mobile phones.

**To Reproduce**
Activate the device toolbar in Chrome developer tools, go to project team administration (e.g. http://localhost:4200/project/0001/collaboration) and play around with the various views.

**Expected behavior**
* Margin (or separate line) between content header elements: Content-title, Select from list, "Create new"-button
* Keep tab bar activated (if possible on smarthpones; otherwise activate navigation menu). 

**Screenshots**
*iPad portrait mode*

![Screen Shot 2020-03-05 at 15 00 08](https://user-images.githubusercontent.com/4253580/75989444-91899c00-5ef3-11ea-9a95-4e123f7898f3.png)

*iPhone portrait mode; no tab bar anymore*

![Screen Shot 2020-03-05 at 15 00 30](https://user-images.githubusercontent.com/4253580/75989523-b4b44b80-5ef3-11ea-9ca1-ae4566adba2c.png)

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-375](https://dasch.myjetbrains.com/youtrack/issue/DSP-375)
