### ISSUE TITLE
Redundant configuration

### ISSUE THREAD

**Issue by kilchenmann** [dasch-swiss/knora-app#276]
The build-prod script in `package.json` doesn't need the `--buildOptimizer=true` option, because it's already set in `angular.json`.

Corresponding files and lines:
- [package.json](https://github.com/dasch-swiss/knora-app/blob/220c20adb38eefd9e295259b76b9159332ed8cf0/package.json#L15)
- [angular.json](https://github.com/dasch-swiss/knora-app/blob/220c20adb38eefd9e295259b76b9159332ed8cf0/angular.json#L56)

@flavens I just saw this little detail and to keep the information somewhere I created this issue. Do I have to move it to Youtrack?

**Comment by flavens** [comment]
> @flavens I just saw this little detail and to keep the information somewhere I created this issue. Do I have to move it to Youtrack?
yes, please

**Comment by kilchenmann** [comment]
Moved to Youtrack
