### ISSUE TITLE
Edit list items

### ISSUE THREAD

**Issue by kilchenmann** [dasch-swiss/knora-app#50]
**Is your feature request related to a problem? Please describe.**
In the next release (2019-09) it's possible to create lists and add new item. But there's no possibility yet to edit or delete list items or to reorder them.

**Describe the solution you'd like**
Update list-item-form to edit. 

**Additional context**
This feature needs the implementation of the StringLiteral form component to support multi-language inputs. I already started with a prototype of this form in [knora-ui-playground](https://github.com/dhlab-basel/knora-ui-playground/tree/wip/viewer-resource)

**Comment by kilchenmann** [comment]
In the list editor we read the project shortcode from the IRI. In some cases (e.g. BEOL) the IRI doesn't contain the shortcode and we get some 400-errors from the API. We have to improve the existing solution. (#57)

**Comment by kilchenmann** [comment]
The input field of label has a default max length of 16. This should be fixed by implementing StringLiteral-input field

**Comment by kilchenmann** [comment]
We have to clean up the file / component structure for the lists.

- **list.component** contains a list of lists in expansion panels (mat-accordion module)
- the mat-accordion contains the **list-items.component** done with recursive **list-item.component** and **list-item-form.component** to add / edit list items (an item is the same as node)
- additional there should be a create / edit button to create the list or edit the list-info itself. **list-info-form.component** opens in mat-dialog.

**Comment by kilchenmann** [comment]
Todo:
- [ ] Fix issue with project id; we can't use the shortcode to create the iri [Comment 524880326](https://github.com/dhlab-basel/Kuirl/issues/50#issuecomment-524880326)
- [ ] list-info-form: implement stringLiteral ~~and remove language selection~~
- [ ] clean up file / component structure; make it simpler
- [ ] update dialog component: remove unused list sections
- [ ] language support for stringLiterals; at the moment we read the first item only 
--> what's about one language selector at the top?

**Comment by kilchenmann** [comment]
- Edit list items (rename) is not yet possible: We have to wait for dhlab-basel/Knora#1387 
- Reposition of list item is not yet possible: We have to wait for dhlab-basel/Knora#1388 
- Delete list is not yet possible: We have to wait for dhlab-basel/Knora#1389 

I suggest to prepare everything in Kuirl with status 'disabled' until Knora admin api supports the list editing. Don't forget to update the Knora-ui core module listsService

**Comment by flavens** [comment]
@kilchenmann should we move this issue to the next milestone 10-2019??

**Comment by kilchenmann** [comment]
@flavens: Not sure. Let's see how fast @subotic will be with implementing the knora api part to edit list nodes. Otherwise we can still postpone it...

**Comment by flavens** [comment]
some tasks have been completed + there are some opened issues in knora-api related to this one and already on YouTrack [#1387](https://github.com/dasch-swiss/knora-api/issues/1387), [#1388](https://github.com/dasch-swiss/knora-api/issues/1388) and [#1389](https://github.com/dasch-swiss/knora-api/issues/1389)
