### ISSUE TITLE
Complete User Guide

### ISSUE THREAD

**Issue by flavens** [dasch-swiss/knora-app#59]
- [x] Replace mockups by screen shots
- [x] Add doc about lists
- [x] Complete doc about data model 
- [x] Complete doc about syntax search

**Comment by kilchenmann** [comment]
@flavens: I already moved the documentation to the new main [docs repository](https://github.com/dasch-swiss/dsp-docs). We have to update the documentation there

**Comment by kilchenmann** [comment]
As I moved the documentation, we can delete the docs folder in this repo? @flavens do you agree?

**Comment by kilchenmann** [comment]
The documentation has been moved to [dasch-swiss/dsp-docs](https://github.com/dasch-swiss/dsp-docs)

Issue closed by PR #93
