### ISSUE TITLE
Test web app to improve user guide

### ISSUE THREAD

**Issue by flavens** [dasch-swiss/knora-app#60]
Perform user testing to improve the current user interface and complete the user guide. Gaby, Martin Mattmüller (BEOL)?, Regula and the Lausanne will be part of this testing phase.

**Comment by flavens** [comment]
Will happen with Gaby, Marion, Rita and Regula between November 6th and November 8th.

**Comment by kilchenmann** [comment]
@flavens What's the state of this issue? It's in the milestone 2019-11... The first testing phase is done. Can we close the issue or set new milestone?

**Comment by flavens** [comment]
@kilchenmann It's done, I close it
