### ISSUE TITLE
Edit resource: Richtext editor

### ISSUE THREAD

**Issue by kilchenmann** [dasch-swiss/knora-app#61]
**Is your feature request related to a problem? Please describe.**
When we have to edit a resource, we edit the single property fields. For them we already have form elements in knora-ui viewer and search module. We have to combine them in viewer. And we need additional form fields like a richtext-editor.

**Describe the solution you'd like**
For the richtext-editor I just found this nice article: **How to Add Rich Text Editor to an Angular App with Localization**
https://medium.com/@hohanga/how-to-add-rich-text-editor-to-an-angular-app-with-localization-ecc7f7238294

**Describe alternatives you've considered**
The article is about CK-editor which we already used in Salsah. There was no other editor who fulfilled our conditions. Probably there are other ones, but we should try with CK-editor again

**Comment by kilchenmann** [comment]
Another article about ckEditor: **A Detailed Approach to Setting Up CKEditor with Angular**
https://medium.com/swlh/a-detailed-approach-of-setting-up-ckeditor-with-angular-e546610157ba

**Comment by flavens** [comment]
this issue has been moved to YouTrack: https://dasch.myjetbrains.com/youtrack/issue/DSP-279
