### ISSUE TITLE
Ontology Editor

### ISSUE THREAD

**Issue by flavens** [dasch-swiss/knora-app#64]
Implement the ontology editor. 
To create an ontology, add resources classes, add properties to a class, edit.

**Comment by subotic** [comment]
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | Stage | State
----- | --------- | --------- | ----- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [feat(ontology-editor): Add resource classes #63](https://github.com/dhlab-basel/Kuirl/issues/63)  [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/J18Y/issues/9907438) | 2019-11 | flavens, kilchenmann | stage/backlog | Open


###### do-not-edit-end-codetree-epic-issues

**Comment by flavens** [comment]
See [DSP-69](https://dasch.myjetbrains.com/youtrack/issue/DSP-69)
