### ISSUE TITLE
Some users do not have access to manage project membership

### ISSUE THREAD

**Issue by flavens** [dasch-swiss/knora-app#71]
**Describe the bug**

**To Reproduce**

!! Error tested only for the members `Admin Webern` and `Nutzer Webern`.

1. Go to '/system/users'
1. Click on 'User menu > Manage project membership'
1. See error > loading only

**Expected behavior**
Display the member project membership form or disable this functionality for this member.

**Screenshots**
<img width="675" alt="Screen Shot 2019-09-05 at 15 07 09" src="https://user-images.githubusercontent.com/29532462/64344637-25cf8080-cfef-11e9-9a47-c8d6a7388784.png">

**Desktop (please complete the following information):**

- OS: MacOS High Sierra (10.13.6)
- Browser: chrome
- Version 76.0.3809.132 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

N.A.

**Additional context**
N.A.

**Comment by kilchenmann** [comment]
This is an issue on Knora-API side. In case of a special character in the username e.g. '-' Knora responses with an error. There's an open issue about this topic in Knora dhlab-basel/Knora#1286

**Comment by flavens** [comment]
this issue has been moved to YouTrack: [DSP-285](https://dasch.myjetbrains.com/youtrack/issue/DSP-285)
