### ISSUE TITLE
Collaboration information not displayed 

### ISSUE THREAD

**Issue by flavens** [dasch-swiss/knora-app#76]
**Describe the bug**
The collaborators information are not well displayed in the list. There is also an error with the icons (see screen shots).

**To Reproduce**

1. Go to https://app2.test.dasch.swiss/project/0807/collaboration
1. See error

**Expected behavior**
Information well displayed.

**Screenshots**
<img width="1092" alt="Screen Shot 2019-09-09 at 11 16 15" src="https://user-images.githubusercontent.com/29532462/64593036-95f25380-d3ad-11e9-9326-a0693bb3d9d5.png">

**Desktop (please complete the following information):**

- OS: MacOS High Sierra
- Browser: Chrome + Safari
- Version N.A.

**Additional context**
N.A.

**Comment by kilchenmann** [comment]
Probably it's an issue because of the breaking change in Knora: dhlab-basel/Knora#1411 
We should test the groups service in @knora/core module with the latest release of Knora and fix it asap.

**Comment by flavens** [comment]
@kilchenmann I cannot reproduce the error in KUIRL locally... can you?

**Comment by flavens** [comment]
@subotic It seems that the issue may come from the test data on the test server.. In the project, users are set as collaborators (the view is truncated) but in the user's profile, the user is not a member of the related project (manage project membership). 
We resolve temporarily the issue by adding manually users to projects.
