### ISSUE TITLE
Add erase resource (button)

### ISSUE THREAD

**Issue by subotic** [dasch-swiss/knora-app#77]
Route added in Knora-API: https://github.com/dhlab-basel/Knora/issues/1421

**Comment by kilchenmann** [comment]
This needs a new method first in dasch-swiss/knora-ui core module. I will implement it...

**Comment by kilchenmann** [comment]
The delete button will take place in the dasch-swiss/knora-ui repo in @knora/viewer module. I already started with a toolbar in resource viewer: [wip/viewer-resource-toolbar](https://github.com/dasch-swiss/knora-ui/tree/wip/viewer-resource-toolbar)

**Comment by flavens** [comment]
this issue is irrelevant due to the viewer refactoring and the integration of knora-api-js-lib -> close
