### ISSUE TITLE
Update the app name to Skuirl

### ISSUE THREAD

**Issue by flavens** [dasch-swiss/knora-app#89]
**Expected situation:**
I saw on the [user guide](https://github.com/dasch-swiss/dsp-docs/blob/master/docs/user-guide/index.md) that the name Skuirl has already been adopted!! So, if it is actually the case, any title/label _Kuirl_ on the app should be changed to _Skuirl_.

**Comment by kilchenmann** [comment]
Haha...it's official yet 🙈 I hope we can decide and name it on Friday!?

**Comment by kilchenmann** [comment]
The new name is just knora-app
