### ISSUE TITLE
Display the name of the project or ontology in resource view

### ISSUE THREAD

**Issue by flavens** [dasch-swiss/knora-app#91]
**Is your feature request related to a problem? Please describe.**
It's unclear in which project or ontology the resource belongs to, especially when we do full text search in All Projects.

**Describe the solution you'd like**
Display the name of the project and/or the ontology in the resource view, at the top of the page.

**Describe alternatives you've considered**
N.A.

**Additional context**

-> how can we know this resource comes from BEOL?

<img width="931" alt="Screen Shot 2019-09-27 at 10 00 35" src="https://user-images.githubusercontent.com/29532462/65752882-0ae3be00-e10e-11e9-8754-5f7006179b83.png">

**Comment by kilchenmann** [comment]
We have to update the ResourceSequence or ReadResourceSequence in @knora/core to get the project or ontology information. Right now it's missing.

**Comment by kilchenmann** [comment]
I started to implement a toolbar to display this information but also to have a place to add edit, delete, share, etc. buttons. [wip/viewer-resource-toolbar](https://github.com/dasch-swiss/knora-ui/tree/wip/viewer-resource-toolbar) 
At the moment we don't have the project information in the resource object. This has to be implemented first.

**Comment by kilchenmann** [comment]
> At the moment we don't have the project information in the resource object. This has to be implemented first.

With the new resource response from knora-api-js-lib we have all necessary information and I'll implement this toolbar / information header in the @knora/viewer [dasch-swiss/knora-ui/tree/wip/fix-api-js-lib-in-viewer](https://github.com/dasch-swiss/knora-ui/tree/wip/fix-api-js-lib-in-viewer)
