### ISSUE TITLE
Project or system admin should be able to reactivate a suspended user

### ISSUE THREAD

**Issue by flavens** [dasch-swiss/knora-app#99]
**Describe the bug**
As project admin or system admin, it is not possible to reactivate a suspended user in a project. Only the action "Remove user from project" is available in the user action menu.

**To Reproduce**
1. Go to https://[localhost or app2.test.dasch.swiss]/project/0803/collaboration
2. Click on the user action menu of a suspended user
4. See error (only *Remove user from project* action is available)

**Expected behavior**
A project admin or a system admin should be able to reactivate a user. 

**Screenshots**
<img width="981" alt="Screenshot 2019-10-09 at 09 11 51" src="https://user-images.githubusercontent.com/29532462/66465072-715acb80-ea80-11e9-8099-cf85d276931a.png">

**Desktop (please complete the following information):**
 - OS: MacOS Mojave 10.14
 - Browser: chrome 77.0.3865.90 (Official Build) (64-bit)

**Additional context**
N.A.

**Comment by kilchenmann** [comment]
Not sure if a project admin has the rights to change user's status. At the moment a system admin can handle it in the system view / list of users.

**Comment by flavens** [comment]
@subotic is it possible for a project admin to reactivate a "deactivated" user?

**Comment by flavens** [comment]
irrelevant issue - the suspended user list does not exist anymore
